// Mocks generated by Mockito 5.4.4 from annotations
// in smile_id/test/smile_id_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:smile_id/generated/smileid_messages.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterAuthenticationResponse_0 extends _i1.SmartFake
    implements _i2.FlutterAuthenticationResponse {
  _FakeFlutterAuthenticationResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterPrepUploadResponse_1 extends _i1.SmartFake
    implements _i2.FlutterPrepUploadResponse {
  _FakeFlutterPrepUploadResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterEnhancedKycResponse_2 extends _i1.SmartFake
    implements _i2.FlutterEnhancedKycResponse {
  _FakeFlutterEnhancedKycResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterEnhancedKycAsyncResponse_3 extends _i1.SmartFake
    implements _i2.FlutterEnhancedKycAsyncResponse {
  _FakeFlutterEnhancedKycAsyncResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSmartSelfieJobStatusResponse_4 extends _i1.SmartFake
    implements _i2.FlutterSmartSelfieJobStatusResponse {
  _FakeFlutterSmartSelfieJobStatusResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSmartSelfieResponse_5 extends _i1.SmartFake
    implements _i2.FlutterSmartSelfieResponse {
  _FakeFlutterSmartSelfieResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterDocumentVerificationJobStatusResponse_6 extends _i1.SmartFake
    implements _i2.FlutterDocumentVerificationJobStatusResponse {
  _FakeFlutterDocumentVerificationJobStatusResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterBiometricKycJobStatusResponse_7 extends _i1.SmartFake
    implements _i2.FlutterBiometricKycJobStatusResponse {
  _FakeFlutterBiometricKycJobStatusResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterEnhancedDocumentVerificationJobStatusResponse_8
    extends _i1.SmartFake
    implements _i2.FlutterEnhancedDocumentVerificationJobStatusResponse {
  _FakeFlutterEnhancedDocumentVerificationJobStatusResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterProductsConfigResponse_9 extends _i1.SmartFake
    implements _i2.FlutterProductsConfigResponse {
  _FakeFlutterProductsConfigResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterValidDocumentsResponse_10 extends _i1.SmartFake
    implements _i2.FlutterValidDocumentsResponse {
  _FakeFlutterValidDocumentsResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterServicesResponse_11 extends _i1.SmartFake
    implements _i2.FlutterServicesResponse {
  _FakeFlutterServicesResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_12 extends _i1.SmartFake implements Object {
  _FakeObject_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterPartnerParams_13 extends _i1.SmartFake
    implements _i2.FlutterPartnerParams {
  _FakeFlutterPartnerParams_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SmileIDApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmileIDApi extends _i1.Mock implements _i2.SmileIDApi {
  @override
  _i3.Future<void> initializeWithApiKey(
    String? apiKey,
    _i2.FlutterConfig? config,
    bool? useSandbox,
    bool? enableCrashReporting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeWithApiKey,
          [
            apiKey,
            config,
            useSandbox,
            enableCrashReporting,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> initializeWithConfig(
    _i2.FlutterConfig? config,
    bool? useSandbox,
    bool? enableCrashReporting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeWithConfig,
          [
            config,
            useSandbox,
            enableCrashReporting,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> initialize(bool? useSandbox) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [useSandbox],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setCallbackUrl(String? callbackUrl) => (super.noSuchMethod(
        Invocation.method(
          #setCallbackUrl,
          [callbackUrl],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setAllowOfflineMode(bool? allowOfflineMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAllowOfflineMode,
          [allowOfflineMode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getUnsubmittedJobs() => (super.noSuchMethod(
        Invocation.method(
          #getUnsubmittedJobs,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> cleanup(String? jobId) => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [jobId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cleanupJobs(List<String?>? jobIds) => (super.noSuchMethod(
        Invocation.method(
          #cleanupJobs,
          [jobIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> submitJob(
    String? jobId,
    bool? deleteFilesOnSuccess,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitJob,
          [
            jobId,
            deleteFilesOnSuccess,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.FlutterAuthenticationResponse> authenticate(
          _i2.FlutterAuthenticationRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterAuthenticationResponse>.value(
            _FakeFlutterAuthenticationResponse_0(
          this,
          Invocation.method(
            #authenticate,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterAuthenticationResponse>.value(
                _FakeFlutterAuthenticationResponse_0(
          this,
          Invocation.method(
            #authenticate,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterAuthenticationResponse>);

  @override
  _i3.Future<_i2.FlutterPrepUploadResponse> prepUpload(
          _i2.FlutterPrepUploadRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepUpload,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterPrepUploadResponse>.value(
            _FakeFlutterPrepUploadResponse_1(
          this,
          Invocation.method(
            #prepUpload,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterPrepUploadResponse>.value(
                _FakeFlutterPrepUploadResponse_1(
          this,
          Invocation.method(
            #prepUpload,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterPrepUploadResponse>);

  @override
  _i3.Future<void> upload(
    String? url,
    _i2.FlutterUploadRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #upload,
          [
            url,
            request,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.FlutterEnhancedKycResponse> doEnhancedKyc(
          _i2.FlutterEnhancedKycRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #doEnhancedKyc,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterEnhancedKycResponse>.value(
            _FakeFlutterEnhancedKycResponse_2(
          this,
          Invocation.method(
            #doEnhancedKyc,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterEnhancedKycResponse>.value(
                _FakeFlutterEnhancedKycResponse_2(
          this,
          Invocation.method(
            #doEnhancedKyc,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterEnhancedKycResponse>);

  @override
  _i3.Future<_i2.FlutterEnhancedKycAsyncResponse> doEnhancedKycAsync(
          _i2.FlutterEnhancedKycRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #doEnhancedKycAsync,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterEnhancedKycAsyncResponse>.value(
            _FakeFlutterEnhancedKycAsyncResponse_3(
          this,
          Invocation.method(
            #doEnhancedKycAsync,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterEnhancedKycAsyncResponse>.value(
                _FakeFlutterEnhancedKycAsyncResponse_3(
          this,
          Invocation.method(
            #doEnhancedKycAsync,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterEnhancedKycAsyncResponse>);

  @override
  _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse> getSmartSelfieJobStatus(
          _i2.FlutterJobStatusRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartSelfieJobStatus,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse>.value(
            _FakeFlutterSmartSelfieJobStatusResponse_4(
          this,
          Invocation.method(
            #getSmartSelfieJobStatus,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse>.value(
                _FakeFlutterSmartSelfieJobStatusResponse_4(
          this,
          Invocation.method(
            #getSmartSelfieJobStatus,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterSmartSelfieResponse> doSmartSelfieEnrollment(
    String? signature,
    String? timestamp,
    String? selfieImage,
    List<String?>? livenessImages,
    String? userId,
    Map<String?, String?>? partnerParams,
    String? callbackUrl,
    int? sandboxResult,
    bool? allowNewEnroll,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doSmartSelfieEnrollment,
          [
            signature,
            timestamp,
            selfieImage,
            livenessImages,
            userId,
            partnerParams,
            callbackUrl,
            sandboxResult,
            allowNewEnroll,
          ],
        ),
        returnValue: _i3.Future<_i2.FlutterSmartSelfieResponse>.value(
            _FakeFlutterSmartSelfieResponse_5(
          this,
          Invocation.method(
            #doSmartSelfieEnrollment,
            [
              signature,
              timestamp,
              selfieImage,
              livenessImages,
              userId,
              partnerParams,
              callbackUrl,
              sandboxResult,
              allowNewEnroll,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterSmartSelfieResponse>.value(
                _FakeFlutterSmartSelfieResponse_5(
          this,
          Invocation.method(
            #doSmartSelfieEnrollment,
            [
              signature,
              timestamp,
              selfieImage,
              livenessImages,
              userId,
              partnerParams,
              callbackUrl,
              sandboxResult,
              allowNewEnroll,
            ],
          ),
        )),
      ) as _i3.Future<_i2.FlutterSmartSelfieResponse>);

  @override
  _i3.Future<_i2.FlutterSmartSelfieResponse> doSmartSelfieAuthentication(
    String? signature,
    String? timestamp,
    String? selfieImage,
    List<String?>? livenessImages,
    String? userId,
    Map<String?, String?>? partnerParams,
    String? callbackUrl,
    int? sandboxResult,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doSmartSelfieAuthentication,
          [
            signature,
            timestamp,
            selfieImage,
            livenessImages,
            userId,
            partnerParams,
            callbackUrl,
            sandboxResult,
          ],
        ),
        returnValue: _i3.Future<_i2.FlutterSmartSelfieResponse>.value(
            _FakeFlutterSmartSelfieResponse_5(
          this,
          Invocation.method(
            #doSmartSelfieAuthentication,
            [
              signature,
              timestamp,
              selfieImage,
              livenessImages,
              userId,
              partnerParams,
              callbackUrl,
              sandboxResult,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterSmartSelfieResponse>.value(
                _FakeFlutterSmartSelfieResponse_5(
          this,
          Invocation.method(
            #doSmartSelfieAuthentication,
            [
              signature,
              timestamp,
              selfieImage,
              livenessImages,
              userId,
              partnerParams,
              callbackUrl,
              sandboxResult,
            ],
          ),
        )),
      ) as _i3.Future<_i2.FlutterSmartSelfieResponse>);

  @override
  _i3.Future<_i2.FlutterDocumentVerificationJobStatusResponse>
      getDocumentVerificationJobStatus(_i2.FlutterJobStatusRequest? request) =>
          (super.noSuchMethod(
            Invocation.method(
              #getDocumentVerificationJobStatus,
              [request],
            ),
            returnValue: _i3
                .Future<_i2.FlutterDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterDocumentVerificationJobStatusResponse_6(
              this,
              Invocation.method(
                #getDocumentVerificationJobStatus,
                [request],
              ),
            )),
            returnValueForMissingStub: _i3
                .Future<_i2.FlutterDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterDocumentVerificationJobStatusResponse_6(
              this,
              Invocation.method(
                #getDocumentVerificationJobStatus,
                [request],
              ),
            )),
          ) as _i3.Future<_i2.FlutterDocumentVerificationJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterBiometricKycJobStatusResponse> getBiometricKycJobStatus(
          _i2.FlutterJobStatusRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBiometricKycJobStatus,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>.value(
            _FakeFlutterBiometricKycJobStatusResponse_7(
          this,
          Invocation.method(
            #getBiometricKycJobStatus,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>.value(
                _FakeFlutterBiometricKycJobStatusResponse_7(
          this,
          Invocation.method(
            #getBiometricKycJobStatus,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterEnhancedDocumentVerificationJobStatusResponse>
      getEnhancedDocumentVerificationJobStatus(
              _i2.FlutterJobStatusRequest? request) =>
          (super.noSuchMethod(
            Invocation.method(
              #getEnhancedDocumentVerificationJobStatus,
              [request],
            ),
            returnValue: _i3.Future<
                    _i2
                    .FlutterEnhancedDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterEnhancedDocumentVerificationJobStatusResponse_8(
              this,
              Invocation.method(
                #getEnhancedDocumentVerificationJobStatus,
                [request],
              ),
            )),
            returnValueForMissingStub: _i3.Future<
                    _i2
                    .FlutterEnhancedDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterEnhancedDocumentVerificationJobStatusResponse_8(
              this,
              Invocation.method(
                #getEnhancedDocumentVerificationJobStatus,
                [request],
              ),
            )),
          ) as _i3.Future<
              _i2.FlutterEnhancedDocumentVerificationJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterProductsConfigResponse> getProductsConfig(
          _i2.FlutterProductsConfigRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsConfig,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterProductsConfigResponse>.value(
            _FakeFlutterProductsConfigResponse_9(
          this,
          Invocation.method(
            #getProductsConfig,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterProductsConfigResponse>.value(
                _FakeFlutterProductsConfigResponse_9(
          this,
          Invocation.method(
            #getProductsConfig,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterProductsConfigResponse>);

  @override
  _i3.Future<_i2.FlutterValidDocumentsResponse> getValidDocuments(
          _i2.FlutterProductsConfigRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getValidDocuments,
          [request],
        ),
        returnValue: _i3.Future<_i2.FlutterValidDocumentsResponse>.value(
            _FakeFlutterValidDocumentsResponse_10(
          this,
          Invocation.method(
            #getValidDocuments,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterValidDocumentsResponse>.value(
                _FakeFlutterValidDocumentsResponse_10(
          this,
          Invocation.method(
            #getValidDocuments,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.FlutterValidDocumentsResponse>);

  @override
  _i3.Future<_i2.FlutterServicesResponse> getServices() => (super.noSuchMethod(
        Invocation.method(
          #getServices,
          [],
        ),
        returnValue: _i3.Future<_i2.FlutterServicesResponse>.value(
            _FakeFlutterServicesResponse_11(
          this,
          Invocation.method(
            #getServices,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterServicesResponse>.value(
                _FakeFlutterServicesResponse_11(
          this,
          Invocation.method(
            #getServices,
            [],
          ),
        )),
      ) as _i3.Future<_i2.FlutterServicesResponse>);

  @override
  _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse> pollSmartSelfieJobStatus(
    _i2.FlutterJobStatusRequest? request,
    int? interval,
    int? numAttempts,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pollSmartSelfieJobStatus,
          [
            request,
            interval,
            numAttempts,
          ],
        ),
        returnValue: _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse>.value(
            _FakeFlutterSmartSelfieJobStatusResponse_4(
          this,
          Invocation.method(
            #pollSmartSelfieJobStatus,
            [
              request,
              interval,
              numAttempts,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse>.value(
                _FakeFlutterSmartSelfieJobStatusResponse_4(
          this,
          Invocation.method(
            #pollSmartSelfieJobStatus,
            [
              request,
              interval,
              numAttempts,
            ],
          ),
        )),
      ) as _i3.Future<_i2.FlutterSmartSelfieJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterDocumentVerificationJobStatusResponse>
      pollDocumentVerificationJobStatus(
    _i2.FlutterJobStatusRequest? request,
    int? interval,
    int? numAttempts,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #pollDocumentVerificationJobStatus,
              [
                request,
                interval,
                numAttempts,
              ],
            ),
            returnValue: _i3
                .Future<_i2.FlutterDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterDocumentVerificationJobStatusResponse_6(
              this,
              Invocation.method(
                #pollDocumentVerificationJobStatus,
                [
                  request,
                  interval,
                  numAttempts,
                ],
              ),
            )),
            returnValueForMissingStub: _i3
                .Future<_i2.FlutterDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterDocumentVerificationJobStatusResponse_6(
              this,
              Invocation.method(
                #pollDocumentVerificationJobStatus,
                [
                  request,
                  interval,
                  numAttempts,
                ],
              ),
            )),
          ) as _i3.Future<_i2.FlutterDocumentVerificationJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>
      pollBiometricKycJobStatus(
    _i2.FlutterJobStatusRequest? request,
    int? interval,
    int? numAttempts,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #pollBiometricKycJobStatus,
              [
                request,
                interval,
                numAttempts,
              ],
            ),
            returnValue:
                _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>.value(
                    _FakeFlutterBiometricKycJobStatusResponse_7(
              this,
              Invocation.method(
                #pollBiometricKycJobStatus,
                [
                  request,
                  interval,
                  numAttempts,
                ],
              ),
            )),
            returnValueForMissingStub:
                _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>.value(
                    _FakeFlutterBiometricKycJobStatusResponse_7(
              this,
              Invocation.method(
                #pollBiometricKycJobStatus,
                [
                  request,
                  interval,
                  numAttempts,
                ],
              ),
            )),
          ) as _i3.Future<_i2.FlutterBiometricKycJobStatusResponse>);

  @override
  _i3.Future<_i2.FlutterEnhancedDocumentVerificationJobStatusResponse>
      pollEnhancedDocumentVerificationJobStatus(
    _i2.FlutterJobStatusRequest? request,
    int? interval,
    int? numAttempts,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #pollEnhancedDocumentVerificationJobStatus,
              [
                request,
                interval,
                numAttempts,
              ],
            ),
            returnValue: _i3.Future<
                    _i2
                    .FlutterEnhancedDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterEnhancedDocumentVerificationJobStatusResponse_8(
              this,
              Invocation.method(
                #pollEnhancedDocumentVerificationJobStatus,
                [
                  request,
                  interval,
                  numAttempts,
                ],
              ),
            )),
            returnValueForMissingStub: _i3.Future<
                    _i2
                    .FlutterEnhancedDocumentVerificationJobStatusResponse>.value(
                _FakeFlutterEnhancedDocumentVerificationJobStatusResponse_8(
              this,
              Invocation.method(
                #pollEnhancedDocumentVerificationJobStatus,
                [
                  request,
                  interval,
                  numAttempts,
                ],
              ),
            )),
          ) as _i3.Future<
              _i2.FlutterEnhancedDocumentVerificationJobStatusResponse>);
}

/// A class which mocks [FlutterAuthenticationRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterAuthenticationRequest extends _i1.Mock
    implements _i2.FlutterAuthenticationRequest {
  @override
  _i2.FlutterJobType get jobType => (super.noSuchMethod(
        Invocation.getter(#jobType),
        returnValue: _i2.FlutterJobType.enhancedKyc,
        returnValueForMissingStub: _i2.FlutterJobType.enhancedKyc,
      ) as _i2.FlutterJobType);

  @override
  set jobType(_i2.FlutterJobType? _jobType) => super.noSuchMethod(
        Invocation.setter(
          #jobType,
          _jobType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set country(String? _country) => super.noSuchMethod(
        Invocation.setter(
          #country,
          _country,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set idType(String? _idType) => super.noSuchMethod(
        Invocation.setter(
          #idType,
          _idType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set updateEnrolledImage(bool? _updateEnrolledImage) => super.noSuchMethod(
        Invocation.setter(
          #updateEnrolledImage,
          _updateEnrolledImage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set jobId(String? _jobId) => super.noSuchMethod(
        Invocation.setter(
          #jobId,
          _jobId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userId(String? _userId) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          _userId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object encode() => (super.noSuchMethod(
        Invocation.method(
          #encode,
          [],
        ),
        returnValue: _FakeObject_12(
          this,
          Invocation.method(
            #encode,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeObject_12(
          this,
          Invocation.method(
            #encode,
            [],
          ),
        ),
      ) as Object);
}

/// A class which mocks [FlutterEnhancedKycRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterEnhancedKycRequest extends _i1.Mock
    implements _i2.FlutterEnhancedKycRequest {
  @override
  String get country => (super.noSuchMethod(
        Invocation.getter(#country),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#country),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#country),
        ),
      ) as String);

  @override
  set country(String? _country) => super.noSuchMethod(
        Invocation.setter(
          #country,
          _country,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get idType => (super.noSuchMethod(
        Invocation.getter(#idType),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#idType),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#idType),
        ),
      ) as String);

  @override
  set idType(String? _idType) => super.noSuchMethod(
        Invocation.setter(
          #idType,
          _idType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get idNumber => (super.noSuchMethod(
        Invocation.getter(#idNumber),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#idNumber),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#idNumber),
        ),
      ) as String);

  @override
  set idNumber(String? _idNumber) => super.noSuchMethod(
        Invocation.setter(
          #idNumber,
          _idNumber,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set firstName(String? _firstName) => super.noSuchMethod(
        Invocation.setter(
          #firstName,
          _firstName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set middleName(String? _middleName) => super.noSuchMethod(
        Invocation.setter(
          #middleName,
          _middleName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastName(String? _lastName) => super.noSuchMethod(
        Invocation.setter(
          #lastName,
          _lastName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dob(String? _dob) => super.noSuchMethod(
        Invocation.setter(
          #dob,
          _dob,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set phoneNumber(String? _phoneNumber) => super.noSuchMethod(
        Invocation.setter(
          #phoneNumber,
          _phoneNumber,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set bankCode(String? _bankCode) => super.noSuchMethod(
        Invocation.setter(
          #bankCode,
          _bankCode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set callbackUrl(String? _callbackUrl) => super.noSuchMethod(
        Invocation.setter(
          #callbackUrl,
          _callbackUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FlutterPartnerParams get partnerParams => (super.noSuchMethod(
        Invocation.getter(#partnerParams),
        returnValue: _FakeFlutterPartnerParams_13(
          this,
          Invocation.getter(#partnerParams),
        ),
        returnValueForMissingStub: _FakeFlutterPartnerParams_13(
          this,
          Invocation.getter(#partnerParams),
        ),
      ) as _i2.FlutterPartnerParams);

  @override
  set partnerParams(_i2.FlutterPartnerParams? _partnerParams) =>
      super.noSuchMethod(
        Invocation.setter(
          #partnerParams,
          _partnerParams,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get timestamp => (super.noSuchMethod(
        Invocation.getter(#timestamp),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#timestamp),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#timestamp),
        ),
      ) as String);

  @override
  set timestamp(String? _timestamp) => super.noSuchMethod(
        Invocation.setter(
          #timestamp,
          _timestamp,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get signature => (super.noSuchMethod(
        Invocation.getter(#signature),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#signature),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#signature),
        ),
      ) as String);

  @override
  set signature(String? _signature) => super.noSuchMethod(
        Invocation.setter(
          #signature,
          _signature,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object encode() => (super.noSuchMethod(
        Invocation.method(
          #encode,
          [],
        ),
        returnValue: _FakeObject_12(
          this,
          Invocation.method(
            #encode,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeObject_12(
          this,
          Invocation.method(
            #encode,
            [],
          ),
        ),
      ) as Object);
}
