# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "10:00"
      timezone: "America/Los_Angeles"
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "America/Los_Angeles"
    groups:
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      # Group updates together, so that they are all applied in a single PR.
      agp:
        # We often want to hold off on AGP updates, so bump this separately
        patterns:
          - "com.android.*"