// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull {
    return nil
  }
  return value as! T?
}

enum FlutterJobType: Int {
  case enhancedKyc = 0
  case documentVerification = 1
  case biometricKyc = 2
  case enhancedDocumentVerification = 3
  case smartSelfieEnrollment = 4
  case smartSelfieAuthentication = 5
}

enum FlutterJobTypeV2: Int {
  case smartSelfieAuthentication = 0
  case smartSelfieEnrollment = 1
}

enum FlutterImageType: Int {
  case selfieJpgFile = 0
  case idCardJpgFile = 1
  case selfieJpgBase64 = 2
  case idCardJpgBase64 = 3
  case livenessJpgFile = 4
  case idCardRearJpgFile = 5
  case livenessJpgBase64 = 6
  case idCardRearJpgBase64 = 7
}

enum FlutterActionResult: Int {
  case passed = 0
  case completed = 1
  case approved = 2
  case verified = 3
  case provisionallyApproved = 4
  case returned = 5
  case notReturned = 6
  case failed = 7
  case rejected = 8
  case underReview = 9
  case unableToDetermine = 10
  case notApplicable = 11
  case notVerified = 12
  case notDone = 13
  case issuerUnavailable = 14
  case idAuthorityPhotoNotAvailable = 15
  case sentToHumanReview = 16
  case unknown = 17
}

enum FlutterSmartSelfieStatus: Int {
  case approved = 0
  case pending = 1
  case rejected = 2
  case unknown = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterConsentInformation {
  var consentGrantedDate: String
  var personalDetailsConsentGranted: Bool
  var contactInfoConsentGranted: Bool
  var documentInfoConsentGranted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterConsentInformation? {
    let consentGrantedDate = pigeonVar_list[0] as! String
    let personalDetailsConsentGranted = pigeonVar_list[1] as! Bool
    let contactInfoConsentGranted = pigeonVar_list[2] as! Bool
    let documentInfoConsentGranted = pigeonVar_list[3] as! Bool

    return FlutterConsentInformation(
      consentGrantedDate: consentGrantedDate,
      personalDetailsConsentGranted: personalDetailsConsentGranted,
      contactInfoConsentGranted: contactInfoConsentGranted,
      documentInfoConsentGranted: documentInfoConsentGranted
    )
  }

  func toList() -> [Any?] {
    return [
      consentGrantedDate,
      personalDetailsConsentGranted,
      contactInfoConsentGranted,
      documentInfoConsentGranted,
    ]
  }
}

///  Custom values specific to partners can be placed in [extras]
///
/// Generated class from Pigeon that represents data sent in messages.
struct FlutterPartnerParams {
  var jobType: FlutterJobType? = nil
  var jobId: String
  var userId: String
  var extras: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterPartnerParams? {
    let jobType: FlutterJobType? = nilOrValue(pigeonVar_list[0])
    let jobId = pigeonVar_list[1] as! String
    let userId = pigeonVar_list[2] as! String
    let extras: [String?: String?]? = nilOrValue(pigeonVar_list[3])

    return FlutterPartnerParams(
      jobType: jobType,
      jobId: jobId,
      userId: userId,
      extras: extras
    )
  }

  func toList() -> [Any?] {
    return [
      jobType,
      jobId,
      userId,
      extras,
    ]
  }
}

/// The Auth Smile request. Auth Smile serves multiple purposes:
///
/// - It is used to fetch the signature needed for subsequent API requests
/// - It indicates the type of job that will being performed
/// - It is used to fetch consent information for the partner
///
/// [jobType] The type of job that will be performed
/// [country] The country code of the country where the job is being performed. This value is
/// required in order to get back consent information for the partner
/// [idType] The type of ID that will be used for the job. This value is required in order to
/// get back consent information for the partner
/// [updateEnrolledImage] Whether or not the enrolled image should be updated with image
/// submitted for this job
/// [jobId] The job ID to associate with the job. Most often, this will correspond to a unique
/// Job ID within your own system. If not provided, a random job ID will be generated
/// [userId] The user ID to associate with the job. Most often, this will correspond to a unique
/// User ID within your own system. If not provided, a random user ID will be generated
///
/// Generated class from Pigeon that represents data sent in messages.
struct FlutterAuthenticationRequest {
  var jobType: FlutterJobType
  var country: String? = nil
  var idType: String? = nil
  var updateEnrolledImage: Bool? = nil
  var jobId: String? = nil
  var userId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterAuthenticationRequest? {
    let jobType = pigeonVar_list[0] as! FlutterJobType
    let country: String? = nilOrValue(pigeonVar_list[1])
    let idType: String? = nilOrValue(pigeonVar_list[2])
    let updateEnrolledImage: Bool? = nilOrValue(pigeonVar_list[3])
    let jobId: String? = nilOrValue(pigeonVar_list[4])
    let userId: String? = nilOrValue(pigeonVar_list[5])

    return FlutterAuthenticationRequest(
      jobType: jobType,
      country: country,
      idType: idType,
      updateEnrolledImage: updateEnrolledImage,
      jobId: jobId,
      userId: userId
    )
  }

  func toList() -> [Any?] {
    return [
      jobType,
      country,
      idType,
      updateEnrolledImage,
      jobId,
      userId,
    ]
  }
}

/// [consentInfo] is only populated when a country and ID type are provided in the
/// [FlutterAuthenticationRequest]. To get information about *all* countries and ID types instead,
///  [SmileIDService.getProductsConfig]
///
/// [timestamp] is *not* a [DateTime] because technically, any arbitrary value could have been
/// passed to it. This applies to all other timestamp fields in the SDK.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FlutterAuthenticationResponse {
  var success: Bool
  var signature: String
  var timestamp: String
  var partnerParams: FlutterPartnerParams
  var callbackUrl: String? = nil
  var consentInfo: FlutterConsentInfo? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterAuthenticationResponse? {
    let success = pigeonVar_list[0] as! Bool
    let signature = pigeonVar_list[1] as! String
    let timestamp = pigeonVar_list[2] as! String
    let partnerParams = pigeonVar_list[3] as! FlutterPartnerParams
    let callbackUrl: String? = nilOrValue(pigeonVar_list[4])
    let consentInfo: FlutterConsentInfo? = nilOrValue(pigeonVar_list[5])

    return FlutterAuthenticationResponse(
      success: success,
      signature: signature,
      timestamp: timestamp,
      partnerParams: partnerParams,
      callbackUrl: callbackUrl,
      consentInfo: consentInfo
    )
  }

  func toList() -> [Any?] {
    return [
      success,
      signature,
      timestamp,
      partnerParams,
      callbackUrl,
      consentInfo,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterPrepUploadRequest {
  var partnerParams: FlutterPartnerParams
  var callbackUrl: String? = nil
  var allowNewEnroll: Bool
  var partnerId: String
  var timestamp: String
  var signature: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterPrepUploadRequest? {
    let partnerParams = pigeonVar_list[0] as! FlutterPartnerParams
    let callbackUrl: String? = nilOrValue(pigeonVar_list[1])
    let allowNewEnroll = pigeonVar_list[2] as! Bool
    let partnerId = pigeonVar_list[3] as! String
    let timestamp = pigeonVar_list[4] as! String
    let signature = pigeonVar_list[5] as! String

    return FlutterPrepUploadRequest(
      partnerParams: partnerParams,
      callbackUrl: callbackUrl,
      allowNewEnroll: allowNewEnroll,
      partnerId: partnerId,
      timestamp: timestamp,
      signature: signature
    )
  }

  func toList() -> [Any?] {
    return [
      partnerParams,
      callbackUrl,
      allowNewEnroll,
      partnerId,
      timestamp,
      signature,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterPrepUploadResponse {
  var code: String
  var refId: String
  var uploadUrl: String
  var smileJobId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterPrepUploadResponse? {
    let code = pigeonVar_list[0] as! String
    let refId = pigeonVar_list[1] as! String
    let uploadUrl = pigeonVar_list[2] as! String
    let smileJobId = pigeonVar_list[3] as! String

    return FlutterPrepUploadResponse(
      code: code,
      refId: refId,
      uploadUrl: uploadUrl,
      smileJobId: smileJobId
    )
  }

  func toList() -> [Any?] {
    return [
      code,
      refId,
      uploadUrl,
      smileJobId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterUploadRequest {
  var images: [FlutterUploadImageInfo?]
  var idInfo: FlutterIdInfo? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterUploadRequest? {
    let images = pigeonVar_list[0] as! [FlutterUploadImageInfo?]
    let idInfo: FlutterIdInfo? = nilOrValue(pigeonVar_list[1])

    return FlutterUploadRequest(
      images: images,
      idInfo: idInfo
    )
  }

  func toList() -> [Any?] {
    return [
      images,
      idInfo,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterUploadImageInfo {
  var imageTypeId: FlutterImageType
  var imageName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterUploadImageInfo? {
    let imageTypeId = pigeonVar_list[0] as! FlutterImageType
    let imageName = pigeonVar_list[1] as! String

    return FlutterUploadImageInfo(
      imageTypeId: imageTypeId,
      imageName: imageName
    )
  }

  func toList() -> [Any?] {
    return [
      imageTypeId,
      imageName,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterIdInfo {
  var country: String
  var idType: String? = nil
  var idNumber: String? = nil
  var firstName: String? = nil
  var middleName: String? = nil
  var lastName: String? = nil
  var dob: String? = nil
  var bankCode: String? = nil
  var entered: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterIdInfo? {
    let country = pigeonVar_list[0] as! String
    let idType: String? = nilOrValue(pigeonVar_list[1])
    let idNumber: String? = nilOrValue(pigeonVar_list[2])
    let firstName: String? = nilOrValue(pigeonVar_list[3])
    let middleName: String? = nilOrValue(pigeonVar_list[4])
    let lastName: String? = nilOrValue(pigeonVar_list[5])
    let dob: String? = nilOrValue(pigeonVar_list[6])
    let bankCode: String? = nilOrValue(pigeonVar_list[7])
    let entered: Bool? = nilOrValue(pigeonVar_list[8])

    return FlutterIdInfo(
      country: country,
      idType: idType,
      idNumber: idNumber,
      firstName: firstName,
      middleName: middleName,
      lastName: lastName,
      dob: dob,
      bankCode: bankCode,
      entered: entered
    )
  }

  func toList() -> [Any?] {
    return [
      country,
      idType,
      idNumber,
      firstName,
      middleName,
      lastName,
      dob,
      bankCode,
      entered,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterEnhancedKycResponse {
  var smileJobId: String
  var partnerParams: FlutterPartnerParams
  var resultText: String
  var resultCode: String
  var actions: FlutterActions
  var country: String
  var idType: String
  var idNumber: String
  var fullName: String? = nil
  var expirationDate: String? = nil
  var dob: String? = nil
  var base64Photo: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterEnhancedKycResponse? {
    let smileJobId = pigeonVar_list[0] as! String
    let partnerParams = pigeonVar_list[1] as! FlutterPartnerParams
    let resultText = pigeonVar_list[2] as! String
    let resultCode = pigeonVar_list[3] as! String
    let actions = pigeonVar_list[4] as! FlutterActions
    let country = pigeonVar_list[5] as! String
    let idType = pigeonVar_list[6] as! String
    let idNumber = pigeonVar_list[7] as! String
    let fullName: String? = nilOrValue(pigeonVar_list[8])
    let expirationDate: String? = nilOrValue(pigeonVar_list[9])
    let dob: String? = nilOrValue(pigeonVar_list[10])
    let base64Photo: String? = nilOrValue(pigeonVar_list[11])

    return FlutterEnhancedKycResponse(
      smileJobId: smileJobId,
      partnerParams: partnerParams,
      resultText: resultText,
      resultCode: resultCode,
      actions: actions,
      country: country,
      idType: idType,
      idNumber: idNumber,
      fullName: fullName,
      expirationDate: expirationDate,
      dob: dob,
      base64Photo: base64Photo
    )
  }

  func toList() -> [Any?] {
    return [
      smileJobId,
      partnerParams,
      resultText,
      resultCode,
      actions,
      country,
      idType,
      idNumber,
      fullName,
      expirationDate,
      dob,
      base64Photo,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterActions {
  var documentCheck: FlutterActionResult
  var humanReviewCompare: FlutterActionResult
  var humanReviewDocumentCheck: FlutterActionResult
  var humanReviewLivenessCheck: FlutterActionResult
  var humanReviewSelfieCheck: FlutterActionResult
  var humanReviewUpdateSelfie: FlutterActionResult
  var livenessCheck: FlutterActionResult
  var registerSelfie: FlutterActionResult
  var returnPersonalInfo: FlutterActionResult
  var selfieCheck: FlutterActionResult
  var selfieProvided: FlutterActionResult
  var selfieToIdAuthorityCompare: FlutterActionResult
  var selfieToIdCardCompare: FlutterActionResult
  var selfieToRegisteredSelfieCompare: FlutterActionResult
  var updateRegisteredSelfieOnFile: FlutterActionResult
  var verifyDocument: FlutterActionResult
  var verifyIdNumber: FlutterActionResult


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterActions? {
    let documentCheck = pigeonVar_list[0] as! FlutterActionResult
    let humanReviewCompare = pigeonVar_list[1] as! FlutterActionResult
    let humanReviewDocumentCheck = pigeonVar_list[2] as! FlutterActionResult
    let humanReviewLivenessCheck = pigeonVar_list[3] as! FlutterActionResult
    let humanReviewSelfieCheck = pigeonVar_list[4] as! FlutterActionResult
    let humanReviewUpdateSelfie = pigeonVar_list[5] as! FlutterActionResult
    let livenessCheck = pigeonVar_list[6] as! FlutterActionResult
    let registerSelfie = pigeonVar_list[7] as! FlutterActionResult
    let returnPersonalInfo = pigeonVar_list[8] as! FlutterActionResult
    let selfieCheck = pigeonVar_list[9] as! FlutterActionResult
    let selfieProvided = pigeonVar_list[10] as! FlutterActionResult
    let selfieToIdAuthorityCompare = pigeonVar_list[11] as! FlutterActionResult
    let selfieToIdCardCompare = pigeonVar_list[12] as! FlutterActionResult
    let selfieToRegisteredSelfieCompare = pigeonVar_list[13] as! FlutterActionResult
    let updateRegisteredSelfieOnFile = pigeonVar_list[14] as! FlutterActionResult
    let verifyDocument = pigeonVar_list[15] as! FlutterActionResult
    let verifyIdNumber = pigeonVar_list[16] as! FlutterActionResult

    return FlutterActions(
      documentCheck: documentCheck,
      humanReviewCompare: humanReviewCompare,
      humanReviewDocumentCheck: humanReviewDocumentCheck,
      humanReviewLivenessCheck: humanReviewLivenessCheck,
      humanReviewSelfieCheck: humanReviewSelfieCheck,
      humanReviewUpdateSelfie: humanReviewUpdateSelfie,
      livenessCheck: livenessCheck,
      registerSelfie: registerSelfie,
      returnPersonalInfo: returnPersonalInfo,
      selfieCheck: selfieCheck,
      selfieProvided: selfieProvided,
      selfieToIdAuthorityCompare: selfieToIdAuthorityCompare,
      selfieToIdCardCompare: selfieToIdCardCompare,
      selfieToRegisteredSelfieCompare: selfieToRegisteredSelfieCompare,
      updateRegisteredSelfieOnFile: updateRegisteredSelfieOnFile,
      verifyDocument: verifyDocument,
      verifyIdNumber: verifyIdNumber
    )
  }

  func toList() -> [Any?] {
    return [
      documentCheck,
      humanReviewCompare,
      humanReviewDocumentCheck,
      humanReviewLivenessCheck,
      humanReviewSelfieCheck,
      humanReviewUpdateSelfie,
      livenessCheck,
      registerSelfie,
      returnPersonalInfo,
      selfieCheck,
      selfieProvided,
      selfieToIdAuthorityCompare,
      selfieToIdCardCompare,
      selfieToRegisteredSelfieCompare,
      updateRegisteredSelfieOnFile,
      verifyDocument,
      verifyIdNumber,
    ]
  }
}

/// [canAccess] Whether or not the ID type is enabled for the partner
/// [consentRequired] Whether or not consent is required for the ID type
///
/// Generated class from Pigeon that represents data sent in messages.
struct FlutterConsentInfo {
  var canAccess: Bool
  var consentRequired: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterConsentInfo? {
    let canAccess = pigeonVar_list[0] as! Bool
    let consentRequired = pigeonVar_list[1] as! Bool

    return FlutterConsentInfo(
      canAccess: canAccess,
      consentRequired: consentRequired
    )
  }

  func toList() -> [Any?] {
    return [
      canAccess,
      consentRequired,
    ]
  }
}

/// [timestamp] is *not* a [DateTime] because technically, any arbitrary value could have been
/// passed to it. This applies to all other timestamp fields in the SDK.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FlutterEnhancedKycRequest {
  var country: String
  var idType: String
  var idNumber: String
  var firstName: String? = nil
  var middleName: String? = nil
  var lastName: String? = nil
  var dob: String? = nil
  var phoneNumber: String? = nil
  var bankCode: String? = nil
  var callbackUrl: String? = nil
  var partnerParams: FlutterPartnerParams
  var timestamp: String
  var signature: String
  var consentInformation: FlutterConsentInformation


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterEnhancedKycRequest? {
    let country = pigeonVar_list[0] as! String
    let idType = pigeonVar_list[1] as! String
    let idNumber = pigeonVar_list[2] as! String
    let firstName: String? = nilOrValue(pigeonVar_list[3])
    let middleName: String? = nilOrValue(pigeonVar_list[4])
    let lastName: String? = nilOrValue(pigeonVar_list[5])
    let dob: String? = nilOrValue(pigeonVar_list[6])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[7])
    let bankCode: String? = nilOrValue(pigeonVar_list[8])
    let callbackUrl: String? = nilOrValue(pigeonVar_list[9])
    let partnerParams = pigeonVar_list[10] as! FlutterPartnerParams
    let timestamp = pigeonVar_list[11] as! String
    let signature = pigeonVar_list[12] as! String
    let consentInformation = pigeonVar_list[13] as! FlutterConsentInformation

    return FlutterEnhancedKycRequest(
      country: country,
      idType: idType,
      idNumber: idNumber,
      firstName: firstName,
      middleName: middleName,
      lastName: lastName,
      dob: dob,
      phoneNumber: phoneNumber,
      bankCode: bankCode,
      callbackUrl: callbackUrl,
      partnerParams: partnerParams,
      timestamp: timestamp,
      signature: signature,
      consentInformation: consentInformation
    )
  }

  func toList() -> [Any?] {
    return [
      country,
      idType,
      idNumber,
      firstName,
      middleName,
      lastName,
      dob,
      phoneNumber,
      bankCode,
      callbackUrl,
      partnerParams,
      timestamp,
      signature,
      consentInformation,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterEnhancedKycAsyncResponse {
  var success: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterEnhancedKycAsyncResponse? {
    let success = pigeonVar_list[0] as! Bool

    return FlutterEnhancedKycAsyncResponse(
      success: success
    )
  }

  func toList() -> [Any?] {
    return [
      success
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterImageLinks {
  var selfieImageUrl: String? = nil
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterImageLinks? {
    let selfieImageUrl: String? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])

    return FlutterImageLinks(
      selfieImageUrl: selfieImageUrl,
      error: error
    )
  }

  func toList() -> [Any?] {
    return [
      selfieImageUrl,
      error,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterAntifraud {
  var suspectUsers: [FlutterSuspectUser?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterAntifraud? {
    let suspectUsers = pigeonVar_list[0] as! [FlutterSuspectUser?]

    return FlutterAntifraud(
      suspectUsers: suspectUsers
    )
  }

  func toList() -> [Any?] {
    return [
      suspectUsers
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterSuspectUser {
  var reason: String
  var userId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterSuspectUser? {
    let reason = pigeonVar_list[0] as! String
    let userId = pigeonVar_list[1] as! String

    return FlutterSuspectUser(
      reason: reason,
      userId: userId
    )
  }

  func toList() -> [Any?] {
    return [
      reason,
      userId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterJobStatusRequest {
  var userId: String
  var jobId: String
  var includeImageLinks: Bool
  var includeHistory: Bool
  var partnerId: String
  var timestamp: String
  var signature: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterJobStatusRequest? {
    let userId = pigeonVar_list[0] as! String
    let jobId = pigeonVar_list[1] as! String
    let includeImageLinks = pigeonVar_list[2] as! Bool
    let includeHistory = pigeonVar_list[3] as! Bool
    let partnerId = pigeonVar_list[4] as! String
    let timestamp = pigeonVar_list[5] as! String
    let signature = pigeonVar_list[6] as! String

    return FlutterJobStatusRequest(
      userId: userId,
      jobId: jobId,
      includeImageLinks: includeImageLinks,
      includeHistory: includeHistory,
      partnerId: partnerId,
      timestamp: timestamp,
      signature: signature
    )
  }

  func toList() -> [Any?] {
    return [
      userId,
      jobId,
      includeImageLinks,
      includeHistory,
      partnerId,
      timestamp,
      signature,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterSmartSelfieJobResult {
  var actions: FlutterActions
  var resultCode: String
  var resultText: String
  var smileJobId: String
  var partnerParams: FlutterPartnerParams
  var confidence: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterSmartSelfieJobResult? {
    let actions = pigeonVar_list[0] as! FlutterActions
    let resultCode = pigeonVar_list[1] as! String
    let resultText = pigeonVar_list[2] as! String
    let smileJobId = pigeonVar_list[3] as! String
    let partnerParams = pigeonVar_list[4] as! FlutterPartnerParams
    let confidence: Double? = nilOrValue(pigeonVar_list[5])

    return FlutterSmartSelfieJobResult(
      actions: actions,
      resultCode: resultCode,
      resultText: resultText,
      smileJobId: smileJobId,
      partnerParams: partnerParams,
      confidence: confidence
    )
  }

  func toList() -> [Any?] {
    return [
      actions,
      resultCode,
      resultText,
      smileJobId,
      partnerParams,
      confidence,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterSmartSelfieJobStatusResponse {
  var timestamp: String
  var jobComplete: Bool
  var jobSuccess: Bool
  var code: String
  var result: FlutterSmartSelfieJobResult? = nil
  var resultString: String? = nil
  var history: [FlutterSmartSelfieJobResult?]? = nil
  var imageLinks: FlutterImageLinks? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterSmartSelfieJobStatusResponse? {
    let timestamp = pigeonVar_list[0] as! String
    let jobComplete = pigeonVar_list[1] as! Bool
    let jobSuccess = pigeonVar_list[2] as! Bool
    let code = pigeonVar_list[3] as! String
    let result: FlutterSmartSelfieJobResult? = nilOrValue(pigeonVar_list[4])
    let resultString: String? = nilOrValue(pigeonVar_list[5])
    let history: [FlutterSmartSelfieJobResult?]? = nilOrValue(pigeonVar_list[6])
    let imageLinks: FlutterImageLinks? = nilOrValue(pigeonVar_list[7])

    return FlutterSmartSelfieJobStatusResponse(
      timestamp: timestamp,
      jobComplete: jobComplete,
      jobSuccess: jobSuccess,
      code: code,
      result: result,
      resultString: resultString,
      history: history,
      imageLinks: imageLinks
    )
  }

  func toList() -> [Any?] {
    return [
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result,
      resultString,
      history,
      imageLinks,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterSmartSelfieResponse {
  var code: String
  var createdAt: String
  var jobId: String
  var jobType: FlutterJobTypeV2
  var message: String
  var partnerId: String
  var partnerParams: [String?: String?]? = nil
  var status: FlutterSmartSelfieStatus
  var updatedAt: String
  var userId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterSmartSelfieResponse? {
    let code = pigeonVar_list[0] as! String
    let createdAt = pigeonVar_list[1] as! String
    let jobId = pigeonVar_list[2] as! String
    let jobType = pigeonVar_list[3] as! FlutterJobTypeV2
    let message = pigeonVar_list[4] as! String
    let partnerId = pigeonVar_list[5] as! String
    let partnerParams: [String?: String?]? = nilOrValue(pigeonVar_list[6])
    let status = pigeonVar_list[7] as! FlutterSmartSelfieStatus
    let updatedAt = pigeonVar_list[8] as! String
    let userId = pigeonVar_list[9] as! String

    return FlutterSmartSelfieResponse(
      code: code,
      createdAt: createdAt,
      jobId: jobId,
      jobType: jobType,
      message: message,
      partnerId: partnerId,
      partnerParams: partnerParams,
      status: status,
      updatedAt: updatedAt,
      userId: userId
    )
  }

  func toList() -> [Any?] {
    return [
      code,
      createdAt,
      jobId,
      jobType,
      message,
      partnerId,
      partnerParams,
      status,
      updatedAt,
      userId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterDocumentVerificationJobResult {
  var actions: FlutterActions
  var resultCode: String
  var resultText: String
  var smileJobId: String
  var partnerParams: FlutterPartnerParams
  var country: String? = nil
  var idType: String? = nil
  var idNumber: String? = nil
  var fullName: String? = nil
  var dob: String? = nil
  var gender: String? = nil
  var expirationDate: String? = nil
  var documentImageBase64: String? = nil
  var phoneNumber: String? = nil
  var phoneNumber2: String? = nil
  var address: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterDocumentVerificationJobResult? {
    let actions = pigeonVar_list[0] as! FlutterActions
    let resultCode = pigeonVar_list[1] as! String
    let resultText = pigeonVar_list[2] as! String
    let smileJobId = pigeonVar_list[3] as! String
    let partnerParams = pigeonVar_list[4] as! FlutterPartnerParams
    let country: String? = nilOrValue(pigeonVar_list[5])
    let idType: String? = nilOrValue(pigeonVar_list[6])
    let idNumber: String? = nilOrValue(pigeonVar_list[7])
    let fullName: String? = nilOrValue(pigeonVar_list[8])
    let dob: String? = nilOrValue(pigeonVar_list[9])
    let gender: String? = nilOrValue(pigeonVar_list[10])
    let expirationDate: String? = nilOrValue(pigeonVar_list[11])
    let documentImageBase64: String? = nilOrValue(pigeonVar_list[12])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[13])
    let phoneNumber2: String? = nilOrValue(pigeonVar_list[14])
    let address: String? = nilOrValue(pigeonVar_list[15])

    return FlutterDocumentVerificationJobResult(
      actions: actions,
      resultCode: resultCode,
      resultText: resultText,
      smileJobId: smileJobId,
      partnerParams: partnerParams,
      country: country,
      idType: idType,
      idNumber: idNumber,
      fullName: fullName,
      dob: dob,
      gender: gender,
      expirationDate: expirationDate,
      documentImageBase64: documentImageBase64,
      phoneNumber: phoneNumber,
      phoneNumber2: phoneNumber2,
      address: address
    )
  }

  func toList() -> [Any?] {
    return [
      actions,
      resultCode,
      resultText,
      smileJobId,
      partnerParams,
      country,
      idType,
      idNumber,
      fullName,
      dob,
      gender,
      expirationDate,
      documentImageBase64,
      phoneNumber,
      phoneNumber2,
      address,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterDocumentVerificationJobStatusResponse {
  var timestamp: String
  var jobComplete: Bool
  var jobSuccess: Bool
  var code: String
  var result: FlutterDocumentVerificationJobResult? = nil
  var resultString: String? = nil
  var history: [FlutterDocumentVerificationJobResult?]? = nil
  var imageLinks: FlutterImageLinks? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterDocumentVerificationJobStatusResponse? {
    let timestamp = pigeonVar_list[0] as! String
    let jobComplete = pigeonVar_list[1] as! Bool
    let jobSuccess = pigeonVar_list[2] as! Bool
    let code = pigeonVar_list[3] as! String
    let result: FlutterDocumentVerificationJobResult? = nilOrValue(pigeonVar_list[4])
    let resultString: String? = nilOrValue(pigeonVar_list[5])
    let history: [FlutterDocumentVerificationJobResult?]? = nilOrValue(pigeonVar_list[6])
    let imageLinks: FlutterImageLinks? = nilOrValue(pigeonVar_list[7])

    return FlutterDocumentVerificationJobStatusResponse(
      timestamp: timestamp,
      jobComplete: jobComplete,
      jobSuccess: jobSuccess,
      code: code,
      result: result,
      resultString: resultString,
      history: history,
      imageLinks: imageLinks
    )
  }

  func toList() -> [Any?] {
    return [
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result,
      resultString,
      history,
      imageLinks,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterBiometricKycJobResult {
  var actions: FlutterActions
  var resultCode: String
  var resultText: String
  var resultType: String
  var smileJobId: String
  var partnerParams: FlutterPartnerParams
  var antifraud: FlutterAntifraud? = nil
  var dob: String? = nil
  var photoBase64: String? = nil
  var gender: String? = nil
  var idType: String? = nil
  var address: String? = nil
  var country: String? = nil
  var documentImageBase64: String? = nil
  var fullData: [String?: String?]? = nil
  var fullName: String? = nil
  var idNumber: String? = nil
  var phoneNumber: String? = nil
  var phoneNumber2: String? = nil
  var expirationDate: String? = nil
  var secondaryIdNumber: String? = nil
  var idNumberPreviouslyRegistered: Bool? = nil
  var previousRegistrantsUserIds: [String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterBiometricKycJobResult? {
    let actions = pigeonVar_list[0] as! FlutterActions
    let resultCode = pigeonVar_list[1] as! String
    let resultText = pigeonVar_list[2] as! String
    let resultType = pigeonVar_list[3] as! String
    let smileJobId = pigeonVar_list[4] as! String
    let partnerParams = pigeonVar_list[5] as! FlutterPartnerParams
    let antifraud: FlutterAntifraud? = nilOrValue(pigeonVar_list[6])
    let dob: String? = nilOrValue(pigeonVar_list[7])
    let photoBase64: String? = nilOrValue(pigeonVar_list[8])
    let gender: String? = nilOrValue(pigeonVar_list[9])
    let idType: String? = nilOrValue(pigeonVar_list[10])
    let address: String? = nilOrValue(pigeonVar_list[11])
    let country: String? = nilOrValue(pigeonVar_list[12])
    let documentImageBase64: String? = nilOrValue(pigeonVar_list[13])
    let fullData: [String?: String?]? = nilOrValue(pigeonVar_list[14])
    let fullName: String? = nilOrValue(pigeonVar_list[15])
    let idNumber: String? = nilOrValue(pigeonVar_list[16])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[17])
    let phoneNumber2: String? = nilOrValue(pigeonVar_list[18])
    let expirationDate: String? = nilOrValue(pigeonVar_list[19])
    let secondaryIdNumber: String? = nilOrValue(pigeonVar_list[20])
    let idNumberPreviouslyRegistered: Bool? = nilOrValue(pigeonVar_list[21])
    let previousRegistrantsUserIds: [String?]? = nilOrValue(pigeonVar_list[22])

    return FlutterBiometricKycJobResult(
      actions: actions,
      resultCode: resultCode,
      resultText: resultText,
      resultType: resultType,
      smileJobId: smileJobId,
      partnerParams: partnerParams,
      antifraud: antifraud,
      dob: dob,
      photoBase64: photoBase64,
      gender: gender,
      idType: idType,
      address: address,
      country: country,
      documentImageBase64: documentImageBase64,
      fullData: fullData,
      fullName: fullName,
      idNumber: idNumber,
      phoneNumber: phoneNumber,
      phoneNumber2: phoneNumber2,
      expirationDate: expirationDate,
      secondaryIdNumber: secondaryIdNumber,
      idNumberPreviouslyRegistered: idNumberPreviouslyRegistered,
      previousRegistrantsUserIds: previousRegistrantsUserIds
    )
  }

  func toList() -> [Any?] {
    return [
      actions,
      resultCode,
      resultText,
      resultType,
      smileJobId,
      partnerParams,
      antifraud,
      dob,
      photoBase64,
      gender,
      idType,
      address,
      country,
      documentImageBase64,
      fullData,
      fullName,
      idNumber,
      phoneNumber,
      phoneNumber2,
      expirationDate,
      secondaryIdNumber,
      idNumberPreviouslyRegistered,
      previousRegistrantsUserIds,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterBiometricKycJobStatusResponse {
  var timestamp: String
  var jobComplete: Bool
  var jobSuccess: Bool
  var code: String
  var result: FlutterBiometricKycJobResult? = nil
  var resultString: String? = nil
  var history: [FlutterBiometricKycJobResult?]? = nil
  var imageLinks: FlutterImageLinks? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterBiometricKycJobStatusResponse? {
    let timestamp = pigeonVar_list[0] as! String
    let jobComplete = pigeonVar_list[1] as! Bool
    let jobSuccess = pigeonVar_list[2] as! Bool
    let code = pigeonVar_list[3] as! String
    let result: FlutterBiometricKycJobResult? = nilOrValue(pigeonVar_list[4])
    let resultString: String? = nilOrValue(pigeonVar_list[5])
    let history: [FlutterBiometricKycJobResult?]? = nilOrValue(pigeonVar_list[6])
    let imageLinks: FlutterImageLinks? = nilOrValue(pigeonVar_list[7])

    return FlutterBiometricKycJobStatusResponse(
      timestamp: timestamp,
      jobComplete: jobComplete,
      jobSuccess: jobSuccess,
      code: code,
      result: result,
      resultString: resultString,
      history: history,
      imageLinks: imageLinks
    )
  }

  func toList() -> [Any?] {
    return [
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result,
      resultString,
      history,
      imageLinks,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterEnhancedDocumentVerificationJobResult {
  var actions: FlutterActions
  var resultCode: String
  var resultText: String
  var resultType: String
  var smileJobId: String
  var partnerParams: FlutterPartnerParams
  var antifraud: FlutterAntifraud? = nil
  var dob: String? = nil
  var photoBase64: String? = nil
  var gender: String? = nil
  var idType: String? = nil
  var address: String? = nil
  var country: String? = nil
  var documentImageBase64: String? = nil
  var fullData: [String?: String?]? = nil
  var fullName: String? = nil
  var idNumber: String? = nil
  var phoneNumber: String? = nil
  var phoneNumber2: String? = nil
  var expirationDate: String? = nil
  var secondaryIdNumber: String? = nil
  var idNumberPreviouslyRegistered: Bool? = nil
  var previousRegistrantsUserIds: [String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterEnhancedDocumentVerificationJobResult? {
    let actions = pigeonVar_list[0] as! FlutterActions
    let resultCode = pigeonVar_list[1] as! String
    let resultText = pigeonVar_list[2] as! String
    let resultType = pigeonVar_list[3] as! String
    let smileJobId = pigeonVar_list[4] as! String
    let partnerParams = pigeonVar_list[5] as! FlutterPartnerParams
    let antifraud: FlutterAntifraud? = nilOrValue(pigeonVar_list[6])
    let dob: String? = nilOrValue(pigeonVar_list[7])
    let photoBase64: String? = nilOrValue(pigeonVar_list[8])
    let gender: String? = nilOrValue(pigeonVar_list[9])
    let idType: String? = nilOrValue(pigeonVar_list[10])
    let address: String? = nilOrValue(pigeonVar_list[11])
    let country: String? = nilOrValue(pigeonVar_list[12])
    let documentImageBase64: String? = nilOrValue(pigeonVar_list[13])
    let fullData: [String?: String?]? = nilOrValue(pigeonVar_list[14])
    let fullName: String? = nilOrValue(pigeonVar_list[15])
    let idNumber: String? = nilOrValue(pigeonVar_list[16])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[17])
    let phoneNumber2: String? = nilOrValue(pigeonVar_list[18])
    let expirationDate: String? = nilOrValue(pigeonVar_list[19])
    let secondaryIdNumber: String? = nilOrValue(pigeonVar_list[20])
    let idNumberPreviouslyRegistered: Bool? = nilOrValue(pigeonVar_list[21])
    let previousRegistrantsUserIds: [String?]? = nilOrValue(pigeonVar_list[22])

    return FlutterEnhancedDocumentVerificationJobResult(
      actions: actions,
      resultCode: resultCode,
      resultText: resultText,
      resultType: resultType,
      smileJobId: smileJobId,
      partnerParams: partnerParams,
      antifraud: antifraud,
      dob: dob,
      photoBase64: photoBase64,
      gender: gender,
      idType: idType,
      address: address,
      country: country,
      documentImageBase64: documentImageBase64,
      fullData: fullData,
      fullName: fullName,
      idNumber: idNumber,
      phoneNumber: phoneNumber,
      phoneNumber2: phoneNumber2,
      expirationDate: expirationDate,
      secondaryIdNumber: secondaryIdNumber,
      idNumberPreviouslyRegistered: idNumberPreviouslyRegistered,
      previousRegistrantsUserIds: previousRegistrantsUserIds
    )
  }

  func toList() -> [Any?] {
    return [
      actions,
      resultCode,
      resultText,
      resultType,
      smileJobId,
      partnerParams,
      antifraud,
      dob,
      photoBase64,
      gender,
      idType,
      address,
      country,
      documentImageBase64,
      fullData,
      fullName,
      idNumber,
      phoneNumber,
      phoneNumber2,
      expirationDate,
      secondaryIdNumber,
      idNumberPreviouslyRegistered,
      previousRegistrantsUserIds,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterEnhancedDocumentVerificationJobStatusResponse {
  var timestamp: String
  var jobComplete: Bool
  var jobSuccess: Bool
  var code: String
  var result: FlutterEnhancedDocumentVerificationJobResult? = nil
  var resultString: String? = nil
  var history: [FlutterEnhancedDocumentVerificationJobResult?]? = nil
  var imageLinks: FlutterImageLinks? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterEnhancedDocumentVerificationJobStatusResponse? {
    let timestamp = pigeonVar_list[0] as! String
    let jobComplete = pigeonVar_list[1] as! Bool
    let jobSuccess = pigeonVar_list[2] as! Bool
    let code = pigeonVar_list[3] as! String
    let result: FlutterEnhancedDocumentVerificationJobResult? = nilOrValue(pigeonVar_list[4])
    let resultString: String? = nilOrValue(pigeonVar_list[5])
    let history: [FlutterEnhancedDocumentVerificationJobResult?]? = nilOrValue(pigeonVar_list[6])
    let imageLinks: FlutterImageLinks? = nilOrValue(pigeonVar_list[7])

    return FlutterEnhancedDocumentVerificationJobStatusResponse(
      timestamp: timestamp,
      jobComplete: jobComplete,
      jobSuccess: jobSuccess,
      code: code,
      result: result,
      resultString: resultString,
      history: history,
      imageLinks: imageLinks
    )
  }

  func toList() -> [Any?] {
    return [
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result,
      resultString,
      history,
      imageLinks,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterProductsConfigRequest {
  var partnerId: String
  var timestamp: String
  var signature: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterProductsConfigRequest? {
    let partnerId = pigeonVar_list[0] as! String
    let timestamp = pigeonVar_list[1] as! String
    let signature = pigeonVar_list[2] as! String

    return FlutterProductsConfigRequest(
      partnerId: partnerId,
      timestamp: timestamp,
      signature: signature
    )
  }

  func toList() -> [Any?] {
    return [
      partnerId,
      timestamp,
      signature,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterProductsConfigResponse {
  var consentRequired: [String?: [String?]?]
  var idSelection: FlutterIdSelection


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterProductsConfigResponse? {
    let consentRequired = pigeonVar_list[0] as! [String?: [String?]?]
    let idSelection = pigeonVar_list[1] as! FlutterIdSelection

    return FlutterProductsConfigResponse(
      consentRequired: consentRequired,
      idSelection: idSelection
    )
  }

  func toList() -> [Any?] {
    return [
      consentRequired,
      idSelection,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterIdSelection {
  var basicKyc: [String?: [String?]?]
  var biometricKyc: [String?: [String?]?]
  var enhancedKyc: [String?: [String?]?]
  var documentVerification: [String?: [String?]?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterIdSelection? {
    let basicKyc = pigeonVar_list[0] as! [String?: [String?]?]
    let biometricKyc = pigeonVar_list[1] as! [String?: [String?]?]
    let enhancedKyc = pigeonVar_list[2] as! [String?: [String?]?]
    let documentVerification = pigeonVar_list[3] as! [String?: [String?]?]

    return FlutterIdSelection(
      basicKyc: basicKyc,
      biometricKyc: biometricKyc,
      enhancedKyc: enhancedKyc,
      documentVerification: documentVerification
    )
  }

  func toList() -> [Any?] {
    return [
      basicKyc,
      biometricKyc,
      enhancedKyc,
      documentVerification,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterValidDocumentsResponse {
  var validDocuments: [FlutterValidDocument?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterValidDocumentsResponse? {
    let validDocuments = pigeonVar_list[0] as! [FlutterValidDocument?]

    return FlutterValidDocumentsResponse(
      validDocuments: validDocuments
    )
  }

  func toList() -> [Any?] {
    return [
      validDocuments
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterValidDocument {
  var country: FlutterCountry
  var idTypes: [FlutterIdType?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterValidDocument? {
    let country = pigeonVar_list[0] as! FlutterCountry
    let idTypes = pigeonVar_list[1] as! [FlutterIdType?]

    return FlutterValidDocument(
      country: country,
      idTypes: idTypes
    )
  }

  func toList() -> [Any?] {
    return [
      country,
      idTypes,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterCountry {
  var code: String
  var continent: String
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterCountry? {
    let code = pigeonVar_list[0] as! String
    let continent = pigeonVar_list[1] as! String
    let name = pigeonVar_list[2] as! String

    return FlutterCountry(
      code: code,
      continent: continent,
      name: name
    )
  }

  func toList() -> [Any?] {
    return [
      code,
      continent,
      name,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterIdType {
  var code: String
  var example: [String?]
  var hasBack: Bool
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterIdType? {
    let code = pigeonVar_list[0] as! String
    let example = pigeonVar_list[1] as! [String?]
    let hasBack = pigeonVar_list[2] as! Bool
    let name = pigeonVar_list[3] as! String

    return FlutterIdType(
      code: code,
      example: example,
      hasBack: hasBack,
      name: name
    )
  }

  func toList() -> [Any?] {
    return [
      code,
      example,
      hasBack,
      name,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterServicesResponse {
  var bankCodes: [FlutterBankCode?]
  var hostedWeb: FlutterHostedWeb


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterServicesResponse? {
    let bankCodes = pigeonVar_list[0] as! [FlutterBankCode?]
    let hostedWeb = pigeonVar_list[1] as! FlutterHostedWeb

    return FlutterServicesResponse(
      bankCodes: bankCodes,
      hostedWeb: hostedWeb
    )
  }

  func toList() -> [Any?] {
    return [
      bankCodes,
      hostedWeb,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterBankCode {
  var name: String
  var code: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterBankCode? {
    let name = pigeonVar_list[0] as! String
    let code = pigeonVar_list[1] as! String

    return FlutterBankCode(
      name: name,
      code: code
    )
  }

  func toList() -> [Any?] {
    return [
      name,
      code,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterHostedWeb {
  var basicKyc: [String?: FlutterCountryInfo?]
  var biometricKyc: [String?: FlutterCountryInfo?]
  var enhancedKyc: [String?: FlutterCountryInfo?]
  var documentVerification: [String?: FlutterCountryInfo?]
  var enhancedKycSmartSelfie: [String?: FlutterCountryInfo?]
  var enhancedDocumentVerification: [String?: FlutterCountryInfo?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterHostedWeb? {
    let basicKyc = pigeonVar_list[0] as! [String?: FlutterCountryInfo?]
    let biometricKyc = pigeonVar_list[1] as! [String?: FlutterCountryInfo?]
    let enhancedKyc = pigeonVar_list[2] as! [String?: FlutterCountryInfo?]
    let documentVerification = pigeonVar_list[3] as! [String?: FlutterCountryInfo?]
    let enhancedKycSmartSelfie = pigeonVar_list[4] as! [String?: FlutterCountryInfo?]
    let enhancedDocumentVerification = pigeonVar_list[5] as! [String?: FlutterCountryInfo?]

    return FlutterHostedWeb(
      basicKyc: basicKyc,
      biometricKyc: biometricKyc,
      enhancedKyc: enhancedKyc,
      documentVerification: documentVerification,
      enhancedKycSmartSelfie: enhancedKycSmartSelfie,
      enhancedDocumentVerification: enhancedDocumentVerification
    )
  }

  func toList() -> [Any?] {
    return [
      basicKyc,
      biometricKyc,
      enhancedKyc,
      documentVerification,
      enhancedKycSmartSelfie,
      enhancedDocumentVerification,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterCountryInfo {
  var countryCode: String
  var name: String
  var availableIdTypes: [FlutterAvailableIdType?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterCountryInfo? {
    let countryCode = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let availableIdTypes = pigeonVar_list[2] as! [FlutterAvailableIdType?]

    return FlutterCountryInfo(
      countryCode: countryCode,
      name: name,
      availableIdTypes: availableIdTypes
    )
  }

  func toList() -> [Any?] {
    return [
      countryCode,
      name,
      availableIdTypes,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterAvailableIdType {
  var idTypeKey: String
  var label: String
  var requiredFields: [String?]
  var testData: String? = nil
  var idNumberRegex: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterAvailableIdType? {
    let idTypeKey = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let requiredFields = pigeonVar_list[2] as! [String?]
    let testData: String? = nilOrValue(pigeonVar_list[3])
    let idNumberRegex: String? = nilOrValue(pigeonVar_list[4])

    return FlutterAvailableIdType(
      idTypeKey: idTypeKey,
      label: label,
      requiredFields: requiredFields,
      testData: testData,
      idNumberRegex: idNumberRegex
    )
  }

  func toList() -> [Any?] {
    return [
      idTypeKey,
      label,
      requiredFields,
      testData,
      idNumberRegex,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FlutterConfig {
  var partnerId: String
  var authToken: String
  var prodBaseUrl: String
  var sandboxBaseUrl: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterConfig? {
    let partnerId = pigeonVar_list[0] as! String
    let authToken = pigeonVar_list[1] as! String
    let prodBaseUrl = pigeonVar_list[2] as! String
    let sandboxBaseUrl = pigeonVar_list[3] as! String

    return FlutterConfig(
      partnerId: partnerId,
      authToken: authToken,
      prodBaseUrl: prodBaseUrl,
      sandboxBaseUrl: sandboxBaseUrl
    )
  }

  func toList() -> [Any?] {
    return [
      partnerId,
      authToken,
      prodBaseUrl,
      sandboxBaseUrl,
    ]
  }
}

private class SmileIDMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FlutterJobType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FlutterJobTypeV2(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FlutterImageType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FlutterActionResult(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FlutterSmartSelfieStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return FlutterConsentInformation.fromList(self.readValue() as! [Any?])
    case 135:
      return FlutterPartnerParams.fromList(self.readValue() as! [Any?])
    case 136:
      return FlutterAuthenticationRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return FlutterAuthenticationResponse.fromList(self.readValue() as! [Any?])
    case 138:
      return FlutterPrepUploadRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return FlutterPrepUploadResponse.fromList(self.readValue() as! [Any?])
    case 140:
      return FlutterUploadRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return FlutterUploadImageInfo.fromList(self.readValue() as! [Any?])
    case 142:
      return FlutterIdInfo.fromList(self.readValue() as! [Any?])
    case 143:
      return FlutterEnhancedKycResponse.fromList(self.readValue() as! [Any?])
    case 144:
      return FlutterActions.fromList(self.readValue() as! [Any?])
    case 145:
      return FlutterConsentInfo.fromList(self.readValue() as! [Any?])
    case 146:
      return FlutterEnhancedKycRequest.fromList(self.readValue() as! [Any?])
    case 147:
      return FlutterEnhancedKycAsyncResponse.fromList(self.readValue() as! [Any?])
    case 148:
      return FlutterImageLinks.fromList(self.readValue() as! [Any?])
    case 149:
      return FlutterAntifraud.fromList(self.readValue() as! [Any?])
    case 150:
      return FlutterSuspectUser.fromList(self.readValue() as! [Any?])
    case 151:
      return FlutterJobStatusRequest.fromList(self.readValue() as! [Any?])
    case 152:
      return FlutterSmartSelfieJobResult.fromList(self.readValue() as! [Any?])
    case 153:
      return FlutterSmartSelfieJobStatusResponse.fromList(self.readValue() as! [Any?])
    case 154:
      return FlutterSmartSelfieResponse.fromList(self.readValue() as! [Any?])
    case 155:
      return FlutterDocumentVerificationJobResult.fromList(self.readValue() as! [Any?])
    case 156:
      return FlutterDocumentVerificationJobStatusResponse.fromList(self.readValue() as! [Any?])
    case 157:
      return FlutterBiometricKycJobResult.fromList(self.readValue() as! [Any?])
    case 158:
      return FlutterBiometricKycJobStatusResponse.fromList(self.readValue() as! [Any?])
    case 159:
      return FlutterEnhancedDocumentVerificationJobResult.fromList(self.readValue() as! [Any?])
    case 160:
      return FlutterEnhancedDocumentVerificationJobStatusResponse.fromList(self.readValue() as! [Any?])
    case 161:
      return FlutterProductsConfigRequest.fromList(self.readValue() as! [Any?])
    case 162:
      return FlutterProductsConfigResponse.fromList(self.readValue() as! [Any?])
    case 163:
      return FlutterIdSelection.fromList(self.readValue() as! [Any?])
    case 164:
      return FlutterValidDocumentsResponse.fromList(self.readValue() as! [Any?])
    case 165:
      return FlutterValidDocument.fromList(self.readValue() as! [Any?])
    case 166:
      return FlutterCountry.fromList(self.readValue() as! [Any?])
    case 167:
      return FlutterIdType.fromList(self.readValue() as! [Any?])
    case 168:
      return FlutterServicesResponse.fromList(self.readValue() as! [Any?])
    case 169:
      return FlutterBankCode.fromList(self.readValue() as! [Any?])
    case 170:
      return FlutterHostedWeb.fromList(self.readValue() as! [Any?])
    case 171:
      return FlutterCountryInfo.fromList(self.readValue() as! [Any?])
    case 172:
      return FlutterAvailableIdType.fromList(self.readValue() as! [Any?])
    case 173:
      return FlutterConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SmileIDMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FlutterJobType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? FlutterJobTypeV2 {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? FlutterImageType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? FlutterActionResult {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? FlutterSmartSelfieStatus {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? FlutterConsentInformation {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterPartnerParams {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterAuthenticationRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterAuthenticationResponse {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterPrepUploadRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterPrepUploadResponse {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterUploadRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterUploadImageInfo {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterIdInfo {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterEnhancedKycResponse {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterActions {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterConsentInfo {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterEnhancedKycRequest {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterEnhancedKycAsyncResponse {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterImageLinks {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterAntifraud {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterSuspectUser {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterJobStatusRequest {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterSmartSelfieJobResult {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterSmartSelfieJobStatusResponse {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterSmartSelfieResponse {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterDocumentVerificationJobResult {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterDocumentVerificationJobStatusResponse {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterBiometricKycJobResult {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterBiometricKycJobStatusResponse {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterEnhancedDocumentVerificationJobResult {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterEnhancedDocumentVerificationJobStatusResponse {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterProductsConfigRequest {
      super.writeByte(161)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterProductsConfigResponse {
      super.writeByte(162)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterIdSelection {
      super.writeByte(163)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterValidDocumentsResponse {
      super.writeByte(164)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterValidDocument {
      super.writeByte(165)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterCountry {
      super.writeByte(166)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterIdType {
      super.writeByte(167)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterServicesResponse {
      super.writeByte(168)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterBankCode {
      super.writeByte(169)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterHostedWeb {
      super.writeByte(170)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterCountryInfo {
      super.writeByte(171)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterAvailableIdType {
      super.writeByte(172)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterConfig {
      super.writeByte(173)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SmileIDMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SmileIDMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SmileIDMessagesPigeonCodecWriter(data: data)
  }
}

class SmileIDMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SmileIDMessagesPigeonCodec(readerWriter: SmileIDMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SmileIDApi {
  func initializeWithApiKey(apiKey: String, config: FlutterConfig, useSandbox: Bool, enableCrashReporting: Bool) throws
  func initializeWithConfig(config: FlutterConfig, useSandbox: Bool, enableCrashReporting: Bool) throws
  func initialize(useSandbox: Bool) throws
  func setCallbackUrl(callbackUrl: String) throws
  func setAllowOfflineMode(allowOfflineMode: Bool) throws
  func getSubmittedJobs() throws -> [String]
  func getUnsubmittedJobs() throws -> [String]
  func cleanup(jobId: String) throws
  func cleanupJobs(jobIds: [String]) throws
  func submitJob(jobId: String, deleteFilesOnSuccess: Bool) throws
  func authenticate(request: FlutterAuthenticationRequest, completion: @escaping (Result<FlutterAuthenticationResponse, Error>) -> Void)
  func prepUpload(request: FlutterPrepUploadRequest, completion: @escaping (Result<FlutterPrepUploadResponse, Error>) -> Void)
  func upload(url: String, request: FlutterUploadRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func doEnhancedKyc(request: FlutterEnhancedKycRequest, completion: @escaping (Result<FlutterEnhancedKycResponse, Error>) -> Void)
  func doEnhancedKycAsync(request: FlutterEnhancedKycRequest, completion: @escaping (Result<FlutterEnhancedKycAsyncResponse, Error>) -> Void)
  func getSmartSelfieJobStatus(request: FlutterJobStatusRequest, completion: @escaping (Result<FlutterSmartSelfieJobStatusResponse, Error>) -> Void)
  func doSmartSelfieEnrollment(signature: String, timestamp: String, selfieImage: String, livenessImages: [String], userId: String, partnerParams: [String?: String?]?, callbackUrl: String?, sandboxResult: Int64?, allowNewEnroll: Bool?, completion: @escaping (Result<FlutterSmartSelfieResponse, Error>) -> Void)
  func doSmartSelfieAuthentication(signature: String, timestamp: String, selfieImage: String, livenessImages: [String], userId: String, partnerParams: [String?: String?]?, callbackUrl: String?, sandboxResult: Int64?, completion: @escaping (Result<FlutterSmartSelfieResponse, Error>) -> Void)
  func getDocumentVerificationJobStatus(request: FlutterJobStatusRequest, completion: @escaping (Result<FlutterDocumentVerificationJobStatusResponse, Error>) -> Void)
  func getBiometricKycJobStatus(request: FlutterJobStatusRequest, completion: @escaping (Result<FlutterBiometricKycJobStatusResponse, Error>) -> Void)
  func getEnhancedDocumentVerificationJobStatus(request: FlutterJobStatusRequest, completion: @escaping (Result<FlutterEnhancedDocumentVerificationJobStatusResponse, Error>) -> Void)
  func getProductsConfig(request: FlutterProductsConfigRequest, completion: @escaping (Result<FlutterProductsConfigResponse, Error>) -> Void)
  func getValidDocuments(request: FlutterProductsConfigRequest, completion: @escaping (Result<FlutterValidDocumentsResponse, Error>) -> Void)
  func getServices(completion: @escaping (Result<FlutterServicesResponse, Error>) -> Void)
  func pollSmartSelfieJobStatus(request: FlutterJobStatusRequest, interval: Int64, numAttempts: Int64, completion: @escaping (Result<FlutterSmartSelfieJobStatusResponse, Error>) -> Void)
  func pollDocumentVerificationJobStatus(request: FlutterJobStatusRequest, interval: Int64, numAttempts: Int64, completion: @escaping (Result<FlutterDocumentVerificationJobStatusResponse, Error>) -> Void)
  func pollBiometricKycJobStatus(request: FlutterJobStatusRequest, interval: Int64, numAttempts: Int64, completion: @escaping (Result<FlutterBiometricKycJobStatusResponse, Error>) -> Void)
  func pollEnhancedDocumentVerificationJobStatus(request: FlutterJobStatusRequest, interval: Int64, numAttempts: Int64, completion: @escaping (Result<FlutterEnhancedDocumentVerificationJobStatusResponse, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SmileIDApiSetup {
  static var codec: FlutterStandardMessageCodec {
    SmileIDMessagesPigeonCodec.shared
  }

  /// Sets up an instance of `SmileIDApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SmileIDApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeWithApiKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.initializeWithApiKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeWithApiKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        let configArg = args[1] as! FlutterConfig
        let useSandboxArg = args[2] as! Bool
        let enableCrashReportingArg = args[3] as! Bool
        do {
          try api.initializeWithApiKey(apiKey: apiKeyArg, config: configArg, useSandbox: useSandboxArg, enableCrashReporting: enableCrashReportingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeWithApiKeyChannel.setMessageHandler(nil)
    }
    let initializeWithConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.initializeWithConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeWithConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! FlutterConfig
        let useSandboxArg = args[1] as! Bool
        let enableCrashReportingArg = args[2] as! Bool
        do {
          try api.initializeWithConfig(config: configArg, useSandbox: useSandboxArg, enableCrashReporting: enableCrashReportingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeWithConfigChannel.setMessageHandler(nil)
    }
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let useSandboxArg = args[0] as! Bool
        do {
          try api.initialize(useSandbox: useSandboxArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let setCallbackUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.setCallbackUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCallbackUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let callbackUrlArg = args[0] as! String
        do {
          try api.setCallbackUrl(callbackUrl: callbackUrlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCallbackUrlChannel.setMessageHandler(nil)
    }
    let setAllowOfflineModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.setAllowOfflineMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAllowOfflineModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let allowOfflineModeArg = args[0] as! Bool
        do {
          try api.setAllowOfflineMode(allowOfflineMode: allowOfflineModeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAllowOfflineModeChannel.setMessageHandler(nil)
    }
    let getSubmittedJobsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getSubmittedJobs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSubmittedJobsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSubmittedJobs()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSubmittedJobsChannel.setMessageHandler(nil)
    }
    let getUnsubmittedJobsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getUnsubmittedJobs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUnsubmittedJobsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getUnsubmittedJobs()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getUnsubmittedJobsChannel.setMessageHandler(nil)
    }
    let cleanupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.cleanup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cleanupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        do {
          try api.cleanup(jobId: jobIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cleanupChannel.setMessageHandler(nil)
    }
    let cleanupJobsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.cleanupJobs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cleanupJobsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdsArg = args[0] as! [String]
        do {
          try api.cleanupJobs(jobIds: jobIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cleanupJobsChannel.setMessageHandler(nil)
    }
    let submitJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.submitJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        let deleteFilesOnSuccessArg = args[1] as! Bool
        do {
          try api.submitJob(jobId: jobIdArg, deleteFilesOnSuccess: deleteFilesOnSuccessArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      submitJobChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterAuthenticationRequest
        api.authenticate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    let prepUploadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.prepUpload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepUploadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterPrepUploadRequest
        api.prepUpload(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepUploadChannel.setMessageHandler(nil)
    }
    let uploadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.upload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      uploadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let requestArg = args[1] as! FlutterUploadRequest
        api.upload(url: urlArg, request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      uploadChannel.setMessageHandler(nil)
    }
    let doEnhancedKycChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.doEnhancedKyc\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      doEnhancedKycChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterEnhancedKycRequest
        api.doEnhancedKyc(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      doEnhancedKycChannel.setMessageHandler(nil)
    }
    let doEnhancedKycAsyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.doEnhancedKycAsync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      doEnhancedKycAsyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterEnhancedKycRequest
        api.doEnhancedKycAsync(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      doEnhancedKycAsyncChannel.setMessageHandler(nil)
    }
    let getSmartSelfieJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getSmartSelfieJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSmartSelfieJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        api.getSmartSelfieJobStatus(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSmartSelfieJobStatusChannel.setMessageHandler(nil)
    }
    let doSmartSelfieEnrollmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.doSmartSelfieEnrollment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      doSmartSelfieEnrollmentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let signatureArg = args[0] as! String
        let timestampArg = args[1] as! String
        let selfieImageArg = args[2] as! String
        let livenessImagesArg = args[3] as! [String]
        let userIdArg = args[4] as! String
        let partnerParamsArg: [String?: String?]? = nilOrValue(args[5])
        let callbackUrlArg: String? = nilOrValue(args[6])
        let sandboxResultArg: Int64? = nilOrValue(args[7])
        let allowNewEnrollArg: Bool? = nilOrValue(args[8])
        api.doSmartSelfieEnrollment(signature: signatureArg, timestamp: timestampArg, selfieImage: selfieImageArg, livenessImages: livenessImagesArg, userId: userIdArg, partnerParams: partnerParamsArg, callbackUrl: callbackUrlArg, sandboxResult: sandboxResultArg, allowNewEnroll: allowNewEnrollArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      doSmartSelfieEnrollmentChannel.setMessageHandler(nil)
    }
    let doSmartSelfieAuthenticationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.doSmartSelfieAuthentication\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      doSmartSelfieAuthenticationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let signatureArg = args[0] as! String
        let timestampArg = args[1] as! String
        let selfieImageArg = args[2] as! String
        let livenessImagesArg = args[3] as! [String]
        let userIdArg = args[4] as! String
        let partnerParamsArg: [String?: String?]? = nilOrValue(args[5])
        let callbackUrlArg: String? = nilOrValue(args[6])
        let sandboxResultArg: Int64? = nilOrValue(args[7])
        api.doSmartSelfieAuthentication(signature: signatureArg, timestamp: timestampArg, selfieImage: selfieImageArg, livenessImages: livenessImagesArg, userId: userIdArg, partnerParams: partnerParamsArg, callbackUrl: callbackUrlArg, sandboxResult: sandboxResultArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      doSmartSelfieAuthenticationChannel.setMessageHandler(nil)
    }
    let getDocumentVerificationJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getDocumentVerificationJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDocumentVerificationJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        api.getDocumentVerificationJobStatus(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDocumentVerificationJobStatusChannel.setMessageHandler(nil)
    }
    let getBiometricKycJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getBiometricKycJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBiometricKycJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        api.getBiometricKycJobStatus(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBiometricKycJobStatusChannel.setMessageHandler(nil)
    }
    let getEnhancedDocumentVerificationJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getEnhancedDocumentVerificationJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEnhancedDocumentVerificationJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        api.getEnhancedDocumentVerificationJobStatus(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getEnhancedDocumentVerificationJobStatusChannel.setMessageHandler(nil)
    }
    let getProductsConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getProductsConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProductsConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterProductsConfigRequest
        api.getProductsConfig(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getProductsConfigChannel.setMessageHandler(nil)
    }
    let getValidDocumentsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getValidDocuments\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getValidDocumentsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterProductsConfigRequest
        api.getValidDocuments(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getValidDocumentsChannel.setMessageHandler(nil)
    }
    let getServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.getServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getServicesChannel.setMessageHandler { _, reply in
        api.getServices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getServicesChannel.setMessageHandler(nil)
    }
    let pollSmartSelfieJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.pollSmartSelfieJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pollSmartSelfieJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        let intervalArg = args[1] as! Int64
        let numAttemptsArg = args[2] as! Int64
        api.pollSmartSelfieJobStatus(request: requestArg, interval: intervalArg, numAttempts: numAttemptsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pollSmartSelfieJobStatusChannel.setMessageHandler(nil)
    }
    let pollDocumentVerificationJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.pollDocumentVerificationJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pollDocumentVerificationJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        let intervalArg = args[1] as! Int64
        let numAttemptsArg = args[2] as! Int64
        api.pollDocumentVerificationJobStatus(request: requestArg, interval: intervalArg, numAttempts: numAttemptsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pollDocumentVerificationJobStatusChannel.setMessageHandler(nil)
    }
    let pollBiometricKycJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.pollBiometricKycJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pollBiometricKycJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        let intervalArg = args[1] as! Int64
        let numAttemptsArg = args[2] as! Int64
        api.pollBiometricKycJobStatus(request: requestArg, interval: intervalArg, numAttempts: numAttemptsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pollBiometricKycJobStatusChannel.setMessageHandler(nil)
    }
    let pollEnhancedDocumentVerificationJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.smileid.SmileIDApi.pollEnhancedDocumentVerificationJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pollEnhancedDocumentVerificationJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterJobStatusRequest
        let intervalArg = args[1] as! Int64
        let numAttemptsArg = args[2] as! Int64
        api.pollEnhancedDocumentVerificationJobStatus(request: requestArg, interval: intervalArg, numAttempts: numAttemptsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pollEnhancedDocumentVerificationJobStatusChannel.setMessageHandler(nil)
    }
  }
}
