// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum FlutterJobType {
  enhancedKyc,
  documentVerification,
}

enum FlutterImageType {
  selfieJpgFile,
  idCardJpgFile,
  selfieJpgBase64,
  idCardJpgBase64,
  livenessJpgFile,
  idCardRearJpgFile,
  livenessJpgBase64,
  idCardRearJpgBase64,
}

enum FlutterActionResult {
  passed,
  completed,
  approved,
  verified,
  provisionallyApproved,
  returned,
  notReturned,
  failed,
  rejected,
  underReview,
  unableToDetermine,
  notApplicable,
  notVerified,
  notDone,
  issuerUnavailable,
  unknown,
}

///  Custom values specific to partners can be placed in [extras]
class FlutterPartnerParams {
  FlutterPartnerParams({
    this.jobType,
    required this.jobId,
    required this.userId,
    this.extras,
  });

  FlutterJobType? jobType;

  String jobId;

  String userId;

  Map<String?, String?>? extras;

  Object encode() {
    return <Object?>[
      jobType?.index,
      jobId,
      userId,
      extras,
    ];
  }

  static FlutterPartnerParams decode(Object result) {
    result as List<Object?>;
    return FlutterPartnerParams(
      jobType: result[0] != null
          ? FlutterJobType.values[result[0]! as int]
          : null,
      jobId: result[1]! as String,
      userId: result[2]! as String,
      extras: (result[3] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }
}

/// The Auth Smile request. Auth Smile serves multiple purposes:
///
/// - It is used to fetch the signature needed for subsequent API requests
/// - It indicates the type of job that will being performed
/// - It is used to fetch consent information for the partner
///
/// [jobType] The type of job that will be performed
/// [country] The country code of the country where the job is being performed. This value is
/// required in order to get back consent information for the partner
/// [idType] The type of ID that will be used for the job. This value is required in order to
/// get back consent information for the partner
/// [updateEnrolledImage] Whether or not the enrolled image should be updated with image
/// submitted for this job
/// [jobId] The job ID to associate with the job. Most often, this will correspond to a unique
/// Job ID within your own system. If not provided, a random job ID will be generated
/// [userId] The user ID to associate with the job. Most often, this will correspond to a unique
/// User ID within your own system. If not provided, a random user ID will be generated
class FlutterAuthenticationRequest {
  FlutterAuthenticationRequest({
    required this.jobType,
    this.country,
    this.idType,
    this.updateEnrolledImage,
    this.jobId,
    this.userId,
  });

  FlutterJobType jobType;

  String? country;

  String? idType;

  bool? updateEnrolledImage;

  String? jobId;

  String? userId;

  Object encode() {
    return <Object?>[
      jobType.index,
      country,
      idType,
      updateEnrolledImage,
      jobId,
      userId,
    ];
  }

  static FlutterAuthenticationRequest decode(Object result) {
    result as List<Object?>;
    return FlutterAuthenticationRequest(
      jobType: FlutterJobType.values[result[0]! as int],
      country: result[1] as String?,
      idType: result[2] as String?,
      updateEnrolledImage: result[3] as bool?,
      jobId: result[4] as String?,
      userId: result[5] as String?,
    );
  }
}

/// [consentInfo] is only populated when a country and ID type are provided in the
/// [FlutterAuthenticationRequest]. To get information about *all* countries and ID types instead,
///  [SmileIDService.getProductsConfig]
///
/// [timestamp] is *not* a [DateTime] because technically, any arbitrary value could have been
/// passed to it. This applies to all other timestamp fields in the SDK.
class FlutterAuthenticationResponse {
  FlutterAuthenticationResponse({
    required this.success,
    required this.signature,
    required this.timestamp,
    required this.partnerParams,
    this.callbackUrl,
    this.consentInfo,
  });

  bool success;

  String signature;

  String timestamp;

  FlutterPartnerParams partnerParams;

  String? callbackUrl;

  FlutterConsentInfo? consentInfo;

  Object encode() {
    return <Object?>[
      success,
      signature,
      timestamp,
      partnerParams.encode(),
      callbackUrl,
      consentInfo?.encode(),
    ];
  }

  static FlutterAuthenticationResponse decode(Object result) {
    result as List<Object?>;
    return FlutterAuthenticationResponse(
      success: result[0]! as bool,
      signature: result[1]! as String,
      timestamp: result[2]! as String,
      partnerParams: FlutterPartnerParams.decode(result[3]! as List<Object?>),
      callbackUrl: result[4] as String?,
      consentInfo: result[5] != null
          ? FlutterConsentInfo.decode(result[5]! as List<Object?>)
          : null,
    );
  }
}

class FlutterPrepUploadRequest {
  FlutterPrepUploadRequest({
    required this.partnerParams,
    this.callbackUrl,
    required this.allowNewEnroll,
    required this.partnerId,
    required this.timestamp,
    required this.signature,
  });

  FlutterPartnerParams partnerParams;

  String? callbackUrl;

  bool allowNewEnroll;

  String partnerId;

  String timestamp;

  String signature;

  Object encode() {
    return <Object?>[
      partnerParams.encode(),
      callbackUrl,
      allowNewEnroll,
      partnerId,
      timestamp,
      signature,
    ];
  }

  static FlutterPrepUploadRequest decode(Object result) {
    result as List<Object?>;
    return FlutterPrepUploadRequest(
      partnerParams: FlutterPartnerParams.decode(result[0]! as List<Object?>),
      callbackUrl: result[1] as String?,
      allowNewEnroll: result[2]! as bool,
      partnerId: result[3]! as String,
      timestamp: result[4]! as String,
      signature: result[5]! as String,
    );
  }
}

class FlutterPrepUploadResponse {
  FlutterPrepUploadResponse({
    required this.code,
    required this.refId,
    required this.uploadUrl,
    required this.smileJobId,
  });

  String code;

  String refId;

  String uploadUrl;

  String smileJobId;

  Object encode() {
    return <Object?>[
      code,
      refId,
      uploadUrl,
      smileJobId,
    ];
  }

  static FlutterPrepUploadResponse decode(Object result) {
    result as List<Object?>;
    return FlutterPrepUploadResponse(
      code: result[0]! as String,
      refId: result[1]! as String,
      uploadUrl: result[2]! as String,
      smileJobId: result[3]! as String,
    );
  }
}

class FlutterUploadRequest {
  FlutterUploadRequest({
    required this.images,
    this.idInfo,
  });

  List<FlutterUploadImageInfo?> images;

  FlutterIdInfo? idInfo;

  Object encode() {
    return <Object?>[
      images,
      idInfo?.encode(),
    ];
  }

  static FlutterUploadRequest decode(Object result) {
    result as List<Object?>;
    return FlutterUploadRequest(
      images: (result[0] as List<Object?>?)!.cast<FlutterUploadImageInfo?>(),
      idInfo: result[1] != null
          ? FlutterIdInfo.decode(result[1]! as List<Object?>)
          : null,
    );
  }
}

class FlutterUploadImageInfo {
  FlutterUploadImageInfo({
    required this.imageTypeId,
    required this.imageName,
  });

  FlutterImageType imageTypeId;

  String imageName;

  Object encode() {
    return <Object?>[
      imageTypeId.index,
      imageName,
    ];
  }

  static FlutterUploadImageInfo decode(Object result) {
    result as List<Object?>;
    return FlutterUploadImageInfo(
      imageTypeId: FlutterImageType.values[result[0]! as int],
      imageName: result[1]! as String,
    );
  }
}

class FlutterIdInfo {
  FlutterIdInfo({
    required this.country,
    this.idType,
    this.idNumber,
    this.firstName,
    this.middleName,
    this.lastName,
    this.dob,
    this.bankCode,
    this.entered,
  });

  String country;

  String? idType;

  String? idNumber;

  String? firstName;

  String? middleName;

  String? lastName;

  String? dob;

  String? bankCode;

  bool? entered;

  Object encode() {
    return <Object?>[
      country,
      idType,
      idNumber,
      firstName,
      middleName,
      lastName,
      dob,
      bankCode,
      entered,
    ];
  }

  static FlutterIdInfo decode(Object result) {
    result as List<Object?>;
    return FlutterIdInfo(
      country: result[0]! as String,
      idType: result[1] as String?,
      idNumber: result[2] as String?,
      firstName: result[3] as String?,
      middleName: result[4] as String?,
      lastName: result[5] as String?,
      dob: result[6] as String?,
      bankCode: result[7] as String?,
      entered: result[8] as bool?,
    );
  }
}

class FlutterEnhancedKycResponse {
  FlutterEnhancedKycResponse({
    required this.smileJobId,
    required this.partnerParams,
    required this.resultText,
    required this.resultCode,
    required this.actions,
    required this.country,
    required this.idType,
    required this.idNumber,
    this.fullName,
    this.expirationDate,
    this.dob,
    this.base64Photo,
  });

  String smileJobId;

  FlutterPartnerParams partnerParams;

  String resultText;

  String resultCode;

  FlutterActions actions;

  String country;

  String idType;

  String idNumber;

  String? fullName;

  String? expirationDate;

  String? dob;

  String? base64Photo;

  Object encode() {
    return <Object?>[
      smileJobId,
      partnerParams.encode(),
      resultText,
      resultCode,
      actions.encode(),
      country,
      idType,
      idNumber,
      fullName,
      expirationDate,
      dob,
      base64Photo,
    ];
  }

  static FlutterEnhancedKycResponse decode(Object result) {
    result as List<Object?>;
    return FlutterEnhancedKycResponse(
      smileJobId: result[0]! as String,
      partnerParams: FlutterPartnerParams.decode(result[1]! as List<Object?>),
      resultText: result[2]! as String,
      resultCode: result[3]! as String,
      actions: FlutterActions.decode(result[4]! as List<Object?>),
      country: result[5]! as String,
      idType: result[6]! as String,
      idNumber: result[7]! as String,
      fullName: result[8] as String?,
      expirationDate: result[9] as String?,
      dob: result[10] as String?,
      base64Photo: result[11] as String?,
    );
  }
}

class FlutterActions {
  FlutterActions({
    required this.documentCheck,
    required this.humanReviewCompare,
    required this.humanReviewDocumentCheck,
    required this.humanReviewLivenessCheck,
    required this.humanReviewSelfieCheck,
    required this.humanReviewUpdateSelfie,
    required this.livenessCheck,
    required this.registerSelfie,
    required this.returnPersonalInfo,
    required this.selfieCheck,
    required this.selfieProvided,
    required this.selfieToIdAuthorityCompare,
    required this.selfieToIdCardCompare,
    required this.selfieToRegisteredSelfieCompare,
    required this.updateRegisteredSelfieOnFile,
    required this.verifyDocument,
    required this.verifyIdNumber,
  });

  FlutterActionResult documentCheck;

  FlutterActionResult humanReviewCompare;

  FlutterActionResult humanReviewDocumentCheck;

  FlutterActionResult humanReviewLivenessCheck;

  FlutterActionResult humanReviewSelfieCheck;

  FlutterActionResult humanReviewUpdateSelfie;

  FlutterActionResult livenessCheck;

  FlutterActionResult registerSelfie;

  FlutterActionResult returnPersonalInfo;

  FlutterActionResult selfieCheck;

  FlutterActionResult selfieProvided;

  FlutterActionResult selfieToIdAuthorityCompare;

  FlutterActionResult selfieToIdCardCompare;

  FlutterActionResult selfieToRegisteredSelfieCompare;

  FlutterActionResult updateRegisteredSelfieOnFile;

  FlutterActionResult verifyDocument;

  FlutterActionResult verifyIdNumber;

  Object encode() {
    return <Object?>[
      documentCheck.index,
      humanReviewCompare.index,
      humanReviewDocumentCheck.index,
      humanReviewLivenessCheck.index,
      humanReviewSelfieCheck.index,
      humanReviewUpdateSelfie.index,
      livenessCheck.index,
      registerSelfie.index,
      returnPersonalInfo.index,
      selfieCheck.index,
      selfieProvided.index,
      selfieToIdAuthorityCompare.index,
      selfieToIdCardCompare.index,
      selfieToRegisteredSelfieCompare.index,
      updateRegisteredSelfieOnFile.index,
      verifyDocument.index,
      verifyIdNumber.index,
    ];
  }

  static FlutterActions decode(Object result) {
    result as List<Object?>;
    return FlutterActions(
      documentCheck: FlutterActionResult.values[result[0]! as int],
      humanReviewCompare: FlutterActionResult.values[result[1]! as int],
      humanReviewDocumentCheck: FlutterActionResult.values[result[2]! as int],
      humanReviewLivenessCheck: FlutterActionResult.values[result[3]! as int],
      humanReviewSelfieCheck: FlutterActionResult.values[result[4]! as int],
      humanReviewUpdateSelfie: FlutterActionResult.values[result[5]! as int],
      livenessCheck: FlutterActionResult.values[result[6]! as int],
      registerSelfie: FlutterActionResult.values[result[7]! as int],
      returnPersonalInfo: FlutterActionResult.values[result[8]! as int],
      selfieCheck: FlutterActionResult.values[result[9]! as int],
      selfieProvided: FlutterActionResult.values[result[10]! as int],
      selfieToIdAuthorityCompare: FlutterActionResult.values[result[11]! as int],
      selfieToIdCardCompare: FlutterActionResult.values[result[12]! as int],
      selfieToRegisteredSelfieCompare: FlutterActionResult.values[result[13]! as int],
      updateRegisteredSelfieOnFile: FlutterActionResult.values[result[14]! as int],
      verifyDocument: FlutterActionResult.values[result[15]! as int],
      verifyIdNumber: FlutterActionResult.values[result[16]! as int],
    );
  }
}

/// [canAccess] Whether or not the ID type is enabled for the partner
/// [consentRequired] Whether or not consent is required for the ID type
class FlutterConsentInfo {
  FlutterConsentInfo({
    required this.canAccess,
    required this.consentRequired,
  });

  bool canAccess;

  bool consentRequired;

  Object encode() {
    return <Object?>[
      canAccess,
      consentRequired,
    ];
  }

  static FlutterConsentInfo decode(Object result) {
    result as List<Object?>;
    return FlutterConsentInfo(
      canAccess: result[0]! as bool,
      consentRequired: result[1]! as bool,
    );
  }
}

/// [timestamp] is *not* a [DateTime] because technically, any arbitrary value could have been
/// passed to it. This applies to all other timestamp fields in the SDK.
class FlutterEnhancedKycRequest {
  FlutterEnhancedKycRequest({
    required this.country,
    required this.idType,
    required this.idNumber,
    this.firstName,
    this.middleName,
    this.lastName,
    this.dob,
    this.phoneNumber,
    this.bankCode,
    this.callbackUrl,
    required this.partnerParams,
    required this.timestamp,
    required this.signature,
  });

  String country;

  String idType;

  String idNumber;

  String? firstName;

  String? middleName;

  String? lastName;

  String? dob;

  String? phoneNumber;

  String? bankCode;

  String? callbackUrl;

  FlutterPartnerParams partnerParams;

  String timestamp;

  String signature;

  Object encode() {
    return <Object?>[
      country,
      idType,
      idNumber,
      firstName,
      middleName,
      lastName,
      dob,
      phoneNumber,
      bankCode,
      callbackUrl,
      partnerParams.encode(),
      timestamp,
      signature,
    ];
  }

  static FlutterEnhancedKycRequest decode(Object result) {
    result as List<Object?>;
    return FlutterEnhancedKycRequest(
      country: result[0]! as String,
      idType: result[1]! as String,
      idNumber: result[2]! as String,
      firstName: result[3] as String?,
      middleName: result[4] as String?,
      lastName: result[5] as String?,
      dob: result[6] as String?,
      phoneNumber: result[7] as String?,
      bankCode: result[8] as String?,
      callbackUrl: result[9] as String?,
      partnerParams: FlutterPartnerParams.decode(result[10]! as List<Object?>),
      timestamp: result[11]! as String,
      signature: result[12]! as String,
    );
  }
}

class FlutterEnhancedKycAsyncResponse {
  FlutterEnhancedKycAsyncResponse({
    required this.success,
  });

  bool success;

  Object encode() {
    return <Object?>[
      success,
    ];
  }

  static FlutterEnhancedKycAsyncResponse decode(Object result) {
    result as List<Object?>;
    return FlutterEnhancedKycAsyncResponse(
      success: result[0]! as bool,
    );
  }
}

class FlutterImageLinks {
  FlutterImageLinks({
    this.selfieImageUrl,
    this.error,
  });

  String? selfieImageUrl;

  String? error;

  Object encode() {
    return <Object?>[
      selfieImageUrl,
      error,
    ];
  }

  static FlutterImageLinks decode(Object result) {
    result as List<Object?>;
    return FlutterImageLinks(
      selfieImageUrl: result[0] as String?,
      error: result[1] as String?,
    );
  }
}

class FlutterAntifraud {
  FlutterAntifraud({
    required this.suspectUsers,
  });

  List<FlutterSuspectUser?> suspectUsers;

  Object encode() {
    return <Object?>[
      suspectUsers,
    ];
  }

  static FlutterAntifraud decode(Object result) {
    result as List<Object?>;
    return FlutterAntifraud(
      suspectUsers: (result[0] as List<Object?>?)!.cast<FlutterSuspectUser?>(),
    );
  }
}

class FlutterSuspectUser {
  FlutterSuspectUser({
    required this.reason,
    required this.userId,
  });

  String reason;

  String userId;

  Object encode() {
    return <Object?>[
      reason,
      userId,
    ];
  }

  static FlutterSuspectUser decode(Object result) {
    result as List<Object?>;
    return FlutterSuspectUser(
      reason: result[0]! as String,
      userId: result[1]! as String,
    );
  }
}

class FlutterJobStatusRequest {
  FlutterJobStatusRequest({
    required this.userId,
    required this.jobId,
    required this.includeImageLinks,
    required this.includeHistory,
    required this.partnerId,
    required this.timestamp,
    required this.signature,
  });

  String userId;

  String jobId;

  bool includeImageLinks;

  bool includeHistory;

  String partnerId;

  String timestamp;

  String signature;

  Object encode() {
    return <Object?>[
      userId,
      jobId,
      includeImageLinks,
      includeHistory,
      partnerId,
      timestamp,
      signature,
    ];
  }

  static FlutterJobStatusRequest decode(Object result) {
    result as List<Object?>;
    return FlutterJobStatusRequest(
      userId: result[0]! as String,
      jobId: result[1]! as String,
      includeImageLinks: result[2]! as bool,
      includeHistory: result[3]! as bool,
      partnerId: result[4]! as String,
      timestamp: result[5]! as String,
      signature: result[6]! as String,
    );
  }
}

class FlutterSmartSelfieJobResult {
  FlutterSmartSelfieJobResult({
    required this.actions,
    required this.resultCode,
    required this.resultText,
    required this.smileJobId,
    required this.partnerParams,
    this.confidence,
  });

  FlutterActions actions;

  String resultCode;

  String resultText;

  String smileJobId;

  FlutterPartnerParams partnerParams;

  double? confidence;

  Object encode() {
    return <Object?>[
      actions.encode(),
      resultCode,
      resultText,
      smileJobId,
      partnerParams.encode(),
      confidence,
    ];
  }

  static FlutterSmartSelfieJobResult decode(Object result) {
    result as List<Object?>;
    return FlutterSmartSelfieJobResult(
      actions: FlutterActions.decode(result[0]! as List<Object?>),
      resultCode: result[1]! as String,
      resultText: result[2]! as String,
      smileJobId: result[3]! as String,
      partnerParams: FlutterPartnerParams.decode(result[4]! as List<Object?>),
      confidence: result[5] as double?,
    );
  }
}

class FlutterSmartSelfieJobStatusResponse {
  FlutterSmartSelfieJobStatusResponse({
    required this.timestamp,
    required this.jobComplete,
    required this.jobSuccess,
    required this.code,
    this.result,
    this.resultString,
    this.history,
    this.imageLinks,
  });

  String timestamp;

  bool jobComplete;

  bool jobSuccess;

  String code;

  FlutterSmartSelfieJobResult? result;

  String? resultString;

  List<FlutterSmartSelfieJobResult?>? history;

  FlutterImageLinks? imageLinks;

  Object encode() {
    return <Object?>[
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result?.encode(),
      resultString,
      history,
      imageLinks?.encode(),
    ];
  }

  static FlutterSmartSelfieJobStatusResponse decode(Object result) {
    result as List<Object?>;
    return FlutterSmartSelfieJobStatusResponse(
      timestamp: result[0]! as String,
      jobComplete: result[1]! as bool,
      jobSuccess: result[2]! as bool,
      code: result[3]! as String,
      result: result[4] != null
          ? FlutterSmartSelfieJobResult.decode(result[4]! as List<Object?>)
          : null,
      resultString: result[5] as String?,
      history: (result[6] as List<Object?>?)?.cast<FlutterSmartSelfieJobResult?>(),
      imageLinks: result[7] != null
          ? FlutterImageLinks.decode(result[7]! as List<Object?>)
          : null,
    );
  }
}

class FlutterDocumentVerificationJobResult {
  FlutterDocumentVerificationJobResult({
    required this.actions,
    required this.resultCode,
    required this.resultText,
    required this.smileJobId,
    required this.partnerParams,
    this.country,
    this.idType,
    this.idNumber,
    this.fullName,
    this.dob,
    this.gender,
    this.expirationDate,
    this.documentImageBase64,
    this.phoneNumber,
    this.phoneNumber2,
    this.address,
  });

  FlutterActions actions;

  String resultCode;

  String resultText;

  String smileJobId;

  FlutterPartnerParams partnerParams;

  String? country;

  String? idType;

  String? idNumber;

  String? fullName;

  String? dob;

  String? gender;

  String? expirationDate;

  String? documentImageBase64;

  String? phoneNumber;

  String? phoneNumber2;

  String? address;

  Object encode() {
    return <Object?>[
      actions.encode(),
      resultCode,
      resultText,
      smileJobId,
      partnerParams.encode(),
      country,
      idType,
      idNumber,
      fullName,
      dob,
      gender,
      expirationDate,
      documentImageBase64,
      phoneNumber,
      phoneNumber2,
      address,
    ];
  }

  static FlutterDocumentVerificationJobResult decode(Object result) {
    result as List<Object?>;
    return FlutterDocumentVerificationJobResult(
      actions: FlutterActions.decode(result[0]! as List<Object?>),
      resultCode: result[1]! as String,
      resultText: result[2]! as String,
      smileJobId: result[3]! as String,
      partnerParams: FlutterPartnerParams.decode(result[4]! as List<Object?>),
      country: result[5] as String?,
      idType: result[6] as String?,
      idNumber: result[7] as String?,
      fullName: result[8] as String?,
      dob: result[9] as String?,
      gender: result[10] as String?,
      expirationDate: result[11] as String?,
      documentImageBase64: result[12] as String?,
      phoneNumber: result[13] as String?,
      phoneNumber2: result[14] as String?,
      address: result[15] as String?,
    );
  }
}

class FlutterDocumentVerificationJobStatusResponse {
  FlutterDocumentVerificationJobStatusResponse({
    required this.timestamp,
    required this.jobComplete,
    required this.jobSuccess,
    required this.code,
    this.result,
    this.resultString,
    this.history,
    this.imageLinks,
  });

  String timestamp;

  bool jobComplete;

  bool jobSuccess;

  String code;

  FlutterDocumentVerificationJobResult? result;

  String? resultString;

  List<FlutterDocumentVerificationJobResult?>? history;

  FlutterImageLinks? imageLinks;

  Object encode() {
    return <Object?>[
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result?.encode(),
      resultString,
      history,
      imageLinks?.encode(),
    ];
  }

  static FlutterDocumentVerificationJobStatusResponse decode(Object result) {
    result as List<Object?>;
    return FlutterDocumentVerificationJobStatusResponse(
      timestamp: result[0]! as String,
      jobComplete: result[1]! as bool,
      jobSuccess: result[2]! as bool,
      code: result[3]! as String,
      result: result[4] != null
          ? FlutterDocumentVerificationJobResult.decode(result[4]! as List<Object?>)
          : null,
      resultString: result[5] as String?,
      history: (result[6] as List<Object?>?)?.cast<FlutterDocumentVerificationJobResult?>(),
      imageLinks: result[7] != null
          ? FlutterImageLinks.decode(result[7]! as List<Object?>)
          : null,
    );
  }
}

class FlutterBiometricKycJobResult {
  FlutterBiometricKycJobResult({
    required this.actions,
    required this.resultCode,
    required this.resultText,
    required this.resultType,
    required this.smileJobId,
    required this.partnerParams,
    this.antifraud,
    this.dob,
    this.photoBase64,
    this.gender,
    this.idType,
    this.address,
    this.country,
    this.documentImageBase64,
    this.fullData,
    this.fullName,
    this.idNumber,
    this.phoneNumber,
    this.phoneNumber2,
    this.expirationDate,
    this.secondaryIdNumber,
    this.idNumberPreviouslyRegistered,
    this.previousRegistrantsUserIds,
  });

  FlutterActions actions;

  String resultCode;

  String resultText;

  String resultType;

  String smileJobId;

  FlutterPartnerParams partnerParams;

  FlutterAntifraud? antifraud;

  String? dob;

  String? photoBase64;

  String? gender;

  String? idType;

  String? address;

  String? country;

  String? documentImageBase64;

  Map<String?, String?>? fullData;

  String? fullName;

  String? idNumber;

  String? phoneNumber;

  String? phoneNumber2;

  String? expirationDate;

  String? secondaryIdNumber;

  bool? idNumberPreviouslyRegistered;

  List<String?>? previousRegistrantsUserIds;

  Object encode() {
    return <Object?>[
      actions.encode(),
      resultCode,
      resultText,
      resultType,
      smileJobId,
      partnerParams.encode(),
      antifraud?.encode(),
      dob,
      photoBase64,
      gender,
      idType,
      address,
      country,
      documentImageBase64,
      fullData,
      fullName,
      idNumber,
      phoneNumber,
      phoneNumber2,
      expirationDate,
      secondaryIdNumber,
      idNumberPreviouslyRegistered,
      previousRegistrantsUserIds,
    ];
  }

  static FlutterBiometricKycJobResult decode(Object result) {
    result as List<Object?>;
    return FlutterBiometricKycJobResult(
      actions: FlutterActions.decode(result[0]! as List<Object?>),
      resultCode: result[1]! as String,
      resultText: result[2]! as String,
      resultType: result[3]! as String,
      smileJobId: result[4]! as String,
      partnerParams: FlutterPartnerParams.decode(result[5]! as List<Object?>),
      antifraud: result[6] != null
          ? FlutterAntifraud.decode(result[6]! as List<Object?>)
          : null,
      dob: result[7] as String?,
      photoBase64: result[8] as String?,
      gender: result[9] as String?,
      idType: result[10] as String?,
      address: result[11] as String?,
      country: result[12] as String?,
      documentImageBase64: result[13] as String?,
      fullData: (result[14] as Map<Object?, Object?>?)?.cast<String?, String?>(),
      fullName: result[15] as String?,
      idNumber: result[16] as String?,
      phoneNumber: result[17] as String?,
      phoneNumber2: result[18] as String?,
      expirationDate: result[19] as String?,
      secondaryIdNumber: result[20] as String?,
      idNumberPreviouslyRegistered: result[21] as bool?,
      previousRegistrantsUserIds: (result[22] as List<Object?>?)?.cast<String?>(),
    );
  }
}

class FlutterBiometricKycJobStatusResponse {
  FlutterBiometricKycJobStatusResponse({
    required this.timestamp,
    required this.jobComplete,
    required this.jobSuccess,
    required this.code,
    this.result,
    this.resultString,
    this.history,
    this.imageLinks,
  });

  String timestamp;

  bool jobComplete;

  bool jobSuccess;

  String code;

  FlutterBiometricKycJobResult? result;

  String? resultString;

  List<FlutterBiometricKycJobResult?>? history;

  FlutterImageLinks? imageLinks;

  Object encode() {
    return <Object?>[
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result?.encode(),
      resultString,
      history,
      imageLinks?.encode(),
    ];
  }

  static FlutterBiometricKycJobStatusResponse decode(Object result) {
    result as List<Object?>;
    return FlutterBiometricKycJobStatusResponse(
      timestamp: result[0]! as String,
      jobComplete: result[1]! as bool,
      jobSuccess: result[2]! as bool,
      code: result[3]! as String,
      result: result[4] != null
          ? FlutterBiometricKycJobResult.decode(result[4]! as List<Object?>)
          : null,
      resultString: result[5] as String?,
      history: (result[6] as List<Object?>?)?.cast<FlutterBiometricKycJobResult?>(),
      imageLinks: result[7] != null
          ? FlutterImageLinks.decode(result[7]! as List<Object?>)
          : null,
    );
  }
}

class FlutterEnhancedDocumentVerificationJobResult {
  FlutterEnhancedDocumentVerificationJobResult({
    required this.actions,
    required this.resultCode,
    required this.resultText,
    required this.resultType,
    required this.smileJobId,
    required this.partnerParams,
    this.antifraud,
    this.dob,
    this.photoBase64,
    this.gender,
    this.idType,
    this.address,
    this.country,
    this.documentImageBase64,
    this.fullData,
    this.fullName,
    this.idNumber,
    this.phoneNumber,
    this.phoneNumber2,
    this.expirationDate,
    this.secondaryIdNumber,
    this.idNumberPreviouslyRegistered,
    this.previousRegistrantsUserIds,
  });

  FlutterActions actions;

  String resultCode;

  String resultText;

  String resultType;

  String smileJobId;

  FlutterPartnerParams partnerParams;

  FlutterAntifraud? antifraud;

  String? dob;

  String? photoBase64;

  String? gender;

  String? idType;

  String? address;

  String? country;

  String? documentImageBase64;

  Map<String?, String?>? fullData;

  String? fullName;

  String? idNumber;

  String? phoneNumber;

  String? phoneNumber2;

  String? expirationDate;

  String? secondaryIdNumber;

  bool? idNumberPreviouslyRegistered;

  List<String?>? previousRegistrantsUserIds;

  Object encode() {
    return <Object?>[
      actions.encode(),
      resultCode,
      resultText,
      resultType,
      smileJobId,
      partnerParams.encode(),
      antifraud?.encode(),
      dob,
      photoBase64,
      gender,
      idType,
      address,
      country,
      documentImageBase64,
      fullData,
      fullName,
      idNumber,
      phoneNumber,
      phoneNumber2,
      expirationDate,
      secondaryIdNumber,
      idNumberPreviouslyRegistered,
      previousRegistrantsUserIds,
    ];
  }

  static FlutterEnhancedDocumentVerificationJobResult decode(Object result) {
    result as List<Object?>;
    return FlutterEnhancedDocumentVerificationJobResult(
      actions: FlutterActions.decode(result[0]! as List<Object?>),
      resultCode: result[1]! as String,
      resultText: result[2]! as String,
      resultType: result[3]! as String,
      smileJobId: result[4]! as String,
      partnerParams: FlutterPartnerParams.decode(result[5]! as List<Object?>),
      antifraud: result[6] != null
          ? FlutterAntifraud.decode(result[6]! as List<Object?>)
          : null,
      dob: result[7] as String?,
      photoBase64: result[8] as String?,
      gender: result[9] as String?,
      idType: result[10] as String?,
      address: result[11] as String?,
      country: result[12] as String?,
      documentImageBase64: result[13] as String?,
      fullData: (result[14] as Map<Object?, Object?>?)?.cast<String?, String?>(),
      fullName: result[15] as String?,
      idNumber: result[16] as String?,
      phoneNumber: result[17] as String?,
      phoneNumber2: result[18] as String?,
      expirationDate: result[19] as String?,
      secondaryIdNumber: result[20] as String?,
      idNumberPreviouslyRegistered: result[21] as bool?,
      previousRegistrantsUserIds: (result[22] as List<Object?>?)?.cast<String?>(),
    );
  }
}

class FlutterEnhancedDocumentVerificationJobStatusResponse {
  FlutterEnhancedDocumentVerificationJobStatusResponse({
    required this.timestamp,
    required this.jobComplete,
    required this.jobSuccess,
    required this.code,
    this.result,
    this.resultString,
    this.history,
    this.imageLinks,
  });

  String timestamp;

  bool jobComplete;

  bool jobSuccess;

  String code;

  FlutterEnhancedDocumentVerificationJobResult? result;

  String? resultString;

  List<FlutterEnhancedDocumentVerificationJobResult?>? history;

  FlutterImageLinks? imageLinks;

  Object encode() {
    return <Object?>[
      timestamp,
      jobComplete,
      jobSuccess,
      code,
      result?.encode(),
      resultString,
      history,
      imageLinks?.encode(),
    ];
  }

  static FlutterEnhancedDocumentVerificationJobStatusResponse decode(Object result) {
    result as List<Object?>;
    return FlutterEnhancedDocumentVerificationJobStatusResponse(
      timestamp: result[0]! as String,
      jobComplete: result[1]! as bool,
      jobSuccess: result[2]! as bool,
      code: result[3]! as String,
      result: result[4] != null
          ? FlutterEnhancedDocumentVerificationJobResult.decode(result[4]! as List<Object?>)
          : null,
      resultString: result[5] as String?,
      history: (result[6] as List<Object?>?)?.cast<FlutterEnhancedDocumentVerificationJobResult?>(),
      imageLinks: result[7] != null
          ? FlutterImageLinks.decode(result[7]! as List<Object?>)
          : null,
    );
  }
}

class FlutterProductsConfigRequest {
  FlutterProductsConfigRequest({
    required this.partnerId,
    required this.timestamp,
    required this.signature,
  });

  String partnerId;

  String timestamp;

  String signature;

  Object encode() {
    return <Object?>[
      partnerId,
      timestamp,
      signature,
    ];
  }

  static FlutterProductsConfigRequest decode(Object result) {
    result as List<Object?>;
    return FlutterProductsConfigRequest(
      partnerId: result[0]! as String,
      timestamp: result[1]! as String,
      signature: result[2]! as String,
    );
  }
}

class FlutterProductsConfigResponse {
  FlutterProductsConfigResponse({
    required this.consentRequired,
    required this.idSelection,
  });

  Map<String?, List<String?>?> consentRequired;

  FlutterIdSelection idSelection;

  Object encode() {
    return <Object?>[
      consentRequired,
      idSelection.encode(),
    ];
  }

  static FlutterProductsConfigResponse decode(Object result) {
    result as List<Object?>;
    return FlutterProductsConfigResponse(
      consentRequired: (result[0] as Map<Object?, Object?>?)!.cast<String?, List<String?>?>(),
      idSelection: FlutterIdSelection.decode(result[1]! as List<Object?>),
    );
  }
}

class FlutterIdSelection {
  FlutterIdSelection({
    required this.basicKyc,
    required this.biometricKyc,
    required this.enhancedKyc,
    required this.documentVerification,
  });

  Map<String?, List<String?>?> basicKyc;

  Map<String?, List<String?>?> biometricKyc;

  Map<String?, List<String?>?> enhancedKyc;

  Map<String?, List<String?>?> documentVerification;

  Object encode() {
    return <Object?>[
      basicKyc,
      biometricKyc,
      enhancedKyc,
      documentVerification,
    ];
  }

  static FlutterIdSelection decode(Object result) {
    result as List<Object?>;
    return FlutterIdSelection(
      basicKyc: (result[0] as Map<Object?, Object?>?)!.cast<String?, List<String?>?>(),
      biometricKyc: (result[1] as Map<Object?, Object?>?)!.cast<String?, List<String?>?>(),
      enhancedKyc: (result[2] as Map<Object?, Object?>?)!.cast<String?, List<String?>?>(),
      documentVerification: (result[3] as Map<Object?, Object?>?)!.cast<String?, List<String?>?>(),
    );
  }
}

class FlutterValidDocumentsResponse {
  FlutterValidDocumentsResponse({
    required this.validDocuments,
  });

  List<FlutterValidDocument?> validDocuments;

  Object encode() {
    return <Object?>[
      validDocuments,
    ];
  }

  static FlutterValidDocumentsResponse decode(Object result) {
    result as List<Object?>;
    return FlutterValidDocumentsResponse(
      validDocuments: (result[0] as List<Object?>?)!.cast<FlutterValidDocument?>(),
    );
  }
}

class FlutterValidDocument {
  FlutterValidDocument({
    required this.country,
    required this.idTypes,
  });

  FlutterCountry country;

  List<FlutterIdType?> idTypes;

  Object encode() {
    return <Object?>[
      country.encode(),
      idTypes,
    ];
  }

  static FlutterValidDocument decode(Object result) {
    result as List<Object?>;
    return FlutterValidDocument(
      country: FlutterCountry.decode(result[0]! as List<Object?>),
      idTypes: (result[1] as List<Object?>?)!.cast<FlutterIdType?>(),
    );
  }
}

class FlutterCountry {
  FlutterCountry({
    required this.code,
    required this.continent,
    required this.name,
  });

  String code;

  String continent;

  String name;

  Object encode() {
    return <Object?>[
      code,
      continent,
      name,
    ];
  }

  static FlutterCountry decode(Object result) {
    result as List<Object?>;
    return FlutterCountry(
      code: result[0]! as String,
      continent: result[1]! as String,
      name: result[2]! as String,
    );
  }
}

class FlutterIdType {
  FlutterIdType({
    required this.code,
    required this.example,
    required this.hasBack,
    required this.name,
  });

  String code;

  List<String?> example;

  bool hasBack;

  String name;

  Object encode() {
    return <Object?>[
      code,
      example,
      hasBack,
      name,
    ];
  }

  static FlutterIdType decode(Object result) {
    result as List<Object?>;
    return FlutterIdType(
      code: result[0]! as String,
      example: (result[1] as List<Object?>?)!.cast<String?>(),
      hasBack: result[2]! as bool,
      name: result[3]! as String,
    );
  }
}

class FlutterServicesResponse {
  FlutterServicesResponse({
    required this.bankCodes,
    required this.hostedWeb,
  });

  List<FlutterBankCode?> bankCodes;

  FlutterHostedWeb hostedWeb;

  Object encode() {
    return <Object?>[
      bankCodes,
      hostedWeb.encode(),
    ];
  }

  static FlutterServicesResponse decode(Object result) {
    result as List<Object?>;
    return FlutterServicesResponse(
      bankCodes: (result[0] as List<Object?>?)!.cast<FlutterBankCode?>(),
      hostedWeb: FlutterHostedWeb.decode(result[1]! as List<Object?>),
    );
  }
}

class FlutterBankCode {
  FlutterBankCode({
    required this.name,
    required this.code,
  });

  String name;

  String code;

  Object encode() {
    return <Object?>[
      name,
      code,
    ];
  }

  static FlutterBankCode decode(Object result) {
    result as List<Object?>;
    return FlutterBankCode(
      name: result[0]! as String,
      code: result[1]! as String,
    );
  }
}

class FlutterHostedWeb {
  FlutterHostedWeb({
    required this.basicKyc,
    required this.biometricKyc,
    required this.enhancedKyc,
    required this.documentVerification,
    required this.enhancedKycSmartSelfie,
    required this.enhancedDocumentVerification,
  });

  Map<String?, FlutterCountryInfo?> basicKyc;

  Map<String?, FlutterCountryInfo?> biometricKyc;

  Map<String?, FlutterCountryInfo?> enhancedKyc;

  Map<String?, FlutterCountryInfo?> documentVerification;

  Map<String?, FlutterCountryInfo?> enhancedKycSmartSelfie;

  Map<String?, FlutterCountryInfo?> enhancedDocumentVerification;

  Object encode() {
    return <Object?>[
      basicKyc,
      biometricKyc,
      enhancedKyc,
      documentVerification,
      enhancedKycSmartSelfie,
      enhancedDocumentVerification,
    ];
  }

  static FlutterHostedWeb decode(Object result) {
    result as List<Object?>;
    return FlutterHostedWeb(
      basicKyc: (result[0] as Map<Object?, Object?>?)!.cast<String?, FlutterCountryInfo?>(),
      biometricKyc: (result[1] as Map<Object?, Object?>?)!.cast<String?, FlutterCountryInfo?>(),
      enhancedKyc: (result[2] as Map<Object?, Object?>?)!.cast<String?, FlutterCountryInfo?>(),
      documentVerification: (result[3] as Map<Object?, Object?>?)!.cast<String?, FlutterCountryInfo?>(),
      enhancedKycSmartSelfie: (result[4] as Map<Object?, Object?>?)!.cast<String?, FlutterCountryInfo?>(),
      enhancedDocumentVerification: (result[5] as Map<Object?, Object?>?)!.cast<String?, FlutterCountryInfo?>(),
    );
  }
}

class FlutterCountryInfo {
  FlutterCountryInfo({
    required this.countryCode,
    required this.name,
    required this.availableIdTypes,
  });

  String countryCode;

  String name;

  List<FlutterAvailableIdType?> availableIdTypes;

  Object encode() {
    return <Object?>[
      countryCode,
      name,
      availableIdTypes,
    ];
  }

  static FlutterCountryInfo decode(Object result) {
    result as List<Object?>;
    return FlutterCountryInfo(
      countryCode: result[0]! as String,
      name: result[1]! as String,
      availableIdTypes: (result[2] as List<Object?>?)!.cast<FlutterAvailableIdType?>(),
    );
  }
}

class FlutterAvailableIdType {
  FlutterAvailableIdType({
    required this.idTypeKey,
    required this.label,
    required this.requiredFields,
    this.testData,
    this.idNumberRegex,
  });

  String idTypeKey;

  String label;

  List<String?> requiredFields;

  String? testData;

  String? idNumberRegex;

  Object encode() {
    return <Object?>[
      idTypeKey,
      label,
      requiredFields,
      testData,
      idNumberRegex,
    ];
  }

  static FlutterAvailableIdType decode(Object result) {
    result as List<Object?>;
    return FlutterAvailableIdType(
      idTypeKey: result[0]! as String,
      label: result[1]! as String,
      requiredFields: (result[2] as List<Object?>?)!.cast<String?>(),
      testData: result[3] as String?,
      idNumberRegex: result[4] as String?,
    );
  }
}

class _SmileIDApiCodec extends StandardMessageCodec {
  const _SmileIDApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is FlutterActions) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is FlutterAntifraud) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is FlutterAuthenticationRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is FlutterAuthenticationResponse) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is FlutterAvailableIdType) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is FlutterBankCode) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is FlutterBiometricKycJobResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is FlutterBiometricKycJobStatusResponse) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is FlutterConsentInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is FlutterCountry) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is FlutterCountryInfo) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is FlutterDocumentVerificationJobResult) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is FlutterDocumentVerificationJobStatusResponse) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is FlutterEnhancedDocumentVerificationJobResult) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is FlutterEnhancedDocumentVerificationJobStatusResponse) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is FlutterEnhancedKycAsyncResponse) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is FlutterEnhancedKycRequest) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is FlutterEnhancedKycResponse) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is FlutterHostedWeb) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is FlutterIdInfo) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is FlutterIdSelection) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is FlutterIdType) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is FlutterImageLinks) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is FlutterJobStatusRequest) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is FlutterPartnerParams) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is FlutterPrepUploadRequest) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is FlutterPrepUploadResponse) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is FlutterProductsConfigRequest) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else if (value is FlutterProductsConfigResponse) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else if (value is FlutterServicesResponse) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    } else if (value is FlutterSmartSelfieJobResult) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    } else if (value is FlutterSmartSelfieJobStatusResponse) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    } else if (value is FlutterSuspectUser) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    } else if (value is FlutterUploadImageInfo) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    } else if (value is FlutterUploadRequest) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    } else if (value is FlutterValidDocument) {
      buffer.putUint8(163);
      writeValue(buffer, value.encode());
    } else if (value is FlutterValidDocumentsResponse) {
      buffer.putUint8(164);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return FlutterActions.decode(readValue(buffer)!);
      case 129: 
        return FlutterAntifraud.decode(readValue(buffer)!);
      case 130: 
        return FlutterAuthenticationRequest.decode(readValue(buffer)!);
      case 131: 
        return FlutterAuthenticationResponse.decode(readValue(buffer)!);
      case 132: 
        return FlutterAvailableIdType.decode(readValue(buffer)!);
      case 133: 
        return FlutterBankCode.decode(readValue(buffer)!);
      case 134: 
        return FlutterBiometricKycJobResult.decode(readValue(buffer)!);
      case 135: 
        return FlutterBiometricKycJobStatusResponse.decode(readValue(buffer)!);
      case 136: 
        return FlutterConsentInfo.decode(readValue(buffer)!);
      case 137: 
        return FlutterCountry.decode(readValue(buffer)!);
      case 138: 
        return FlutterCountryInfo.decode(readValue(buffer)!);
      case 139: 
        return FlutterDocumentVerificationJobResult.decode(readValue(buffer)!);
      case 140: 
        return FlutterDocumentVerificationJobStatusResponse.decode(readValue(buffer)!);
      case 141: 
        return FlutterEnhancedDocumentVerificationJobResult.decode(readValue(buffer)!);
      case 142: 
        return FlutterEnhancedDocumentVerificationJobStatusResponse.decode(readValue(buffer)!);
      case 143: 
        return FlutterEnhancedKycAsyncResponse.decode(readValue(buffer)!);
      case 144: 
        return FlutterEnhancedKycRequest.decode(readValue(buffer)!);
      case 145: 
        return FlutterEnhancedKycResponse.decode(readValue(buffer)!);
      case 146: 
        return FlutterHostedWeb.decode(readValue(buffer)!);
      case 147: 
        return FlutterIdInfo.decode(readValue(buffer)!);
      case 148: 
        return FlutterIdSelection.decode(readValue(buffer)!);
      case 149: 
        return FlutterIdType.decode(readValue(buffer)!);
      case 150: 
        return FlutterImageLinks.decode(readValue(buffer)!);
      case 151: 
        return FlutterJobStatusRequest.decode(readValue(buffer)!);
      case 152: 
        return FlutterPartnerParams.decode(readValue(buffer)!);
      case 153: 
        return FlutterPrepUploadRequest.decode(readValue(buffer)!);
      case 154: 
        return FlutterPrepUploadResponse.decode(readValue(buffer)!);
      case 155: 
        return FlutterProductsConfigRequest.decode(readValue(buffer)!);
      case 156: 
        return FlutterProductsConfigResponse.decode(readValue(buffer)!);
      case 157: 
        return FlutterServicesResponse.decode(readValue(buffer)!);
      case 158: 
        return FlutterSmartSelfieJobResult.decode(readValue(buffer)!);
      case 159: 
        return FlutterSmartSelfieJobStatusResponse.decode(readValue(buffer)!);
      case 160: 
        return FlutterSuspectUser.decode(readValue(buffer)!);
      case 161: 
        return FlutterUploadImageInfo.decode(readValue(buffer)!);
      case 162: 
        return FlutterUploadRequest.decode(readValue(buffer)!);
      case 163: 
        return FlutterValidDocument.decode(readValue(buffer)!);
      case 164: 
        return FlutterValidDocumentsResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SmileIDApi {
  /// Constructor for [SmileIDApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SmileIDApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _SmileIDApiCodec();

  Future<void> initialize() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.initialize', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setEnvironment(bool arg_useSandbox) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.setEnvironment', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_useSandbox]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setCallbackUrl(String arg_callbackUrl) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.setCallbackUrl', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_callbackUrl]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<FlutterAuthenticationResponse> authenticate(FlutterAuthenticationRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.authenticate', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterAuthenticationResponse?)!;
    }
  }

  Future<FlutterPrepUploadResponse> prepUpload(FlutterPrepUploadRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.prepUpload', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterPrepUploadResponse?)!;
    }
  }

  Future<void> upload(String arg_url, FlutterUploadRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.upload', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_url, arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<FlutterEnhancedKycResponse> doEnhancedKyc(FlutterEnhancedKycRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.doEnhancedKyc', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterEnhancedKycResponse?)!;
    }
  }

  Future<FlutterEnhancedKycAsyncResponse> doEnhancedKycAsync(FlutterEnhancedKycRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.doEnhancedKycAsync', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterEnhancedKycAsyncResponse?)!;
    }
  }

  Future<FlutterSmartSelfieJobStatusResponse> getSmartSelfieJobStatus(FlutterJobStatusRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getSmartSelfieJobStatus', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterSmartSelfieJobStatusResponse?)!;
    }
  }

  Future<FlutterDocumentVerificationJobStatusResponse> getDocumentVerificationJobStatus(FlutterJobStatusRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getDocumentVerificationJobStatus', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterDocumentVerificationJobStatusResponse?)!;
    }
  }

  Future<FlutterBiometricKycJobStatusResponse> getBiometricKycJobStatus(FlutterJobStatusRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getBiometricKycJobStatus', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterBiometricKycJobStatusResponse?)!;
    }
  }

  Future<FlutterEnhancedDocumentVerificationJobStatusResponse> getEnhancedDocumentVerificationJobStatus(FlutterJobStatusRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getEnhancedDocumentVerificationJobStatus', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterEnhancedDocumentVerificationJobStatusResponse?)!;
    }
  }

  Future<FlutterProductsConfigResponse> getProductsConfig(FlutterProductsConfigRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getProductsConfig', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterProductsConfigResponse?)!;
    }
  }

  Future<FlutterValidDocumentsResponse> getValidDocuments(FlutterProductsConfigRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getValidDocuments', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterValidDocumentsResponse?)!;
    }
  }

  Future<FlutterServicesResponse> getServices() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.smileid.SmileIDApi.getServices', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as FlutterServicesResponse?)!;
    }
  }
}
