name: Lint Build and Test (iOS)
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6' # Set the desired Flutter version here
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get && cd sample && flutter pub get && cd ..
      - name: Build iOS Sample App
        run: cd sample && flutter build ios --no-codesign && cd ..
